export const createMockUseRichTextEditor = (overrides: Record<string, unknown> = {}) => ({
  editor: null,
  expandedLocal: ref(false),
  cmd: vi.fn(),
  isActive: vi.fn().mockReturnValue(false),
  currentBlockType: ref('paragraph'),
  onFontSizeChange: vi.fn(),
  textColor: ref('#000000'),
  highlightColor: ref('#ffffff'),
  setFontColor: vi.fn(),
  setHighlightColor: vi.fn(),
  setAlign: vi.fn(),
  isActiveAlign: vi.fn().mockReturnValue(false),
  textAlignStyle: ref({ textAlign: 'left' }),
  canUndo: ref(false),
  canRedo: ref(false),
  undo: vi.fn(),
  redo: vi.fn(),
  toggleLink: vi.fn(),
  clearFormatting: vi.fn(),
  focus: vi.fn(),
  ...overrides,
});
