import type { HomeReviewItem, HomeReviewsContent } from './types';

export const DEFAULT_HOME_REVIEWS: HomeReviewItem[] = [
  {
    id: 'w-henneboh',
    name: 'Wolfgang Henneboh',
    initials: 'W',
    when: 'vor 2 Jahren',
    rating: 5,
    text: 'Ich habe dort eine Hantelbank gekauft (über Ebay), diese Qualität hatte ich vermutlich nirgends gefunden und wenn, dann für sehr viel Geld. Alle Mitarbeiter dort waren sehr freundlich und hilfsbereit. Fazit: Ja Verkäufer, das gilt für alle dort.',
    avatar: { bg: '#6D28D9', text: '#FFFFFF' },
  },
  {
    id: 't-dressler',
    name: 'Tim Dressler',
    initials: 'T',
    when: 'vor einem Jahr',
    rating: 5,
    text: 'Ich bin absolut begeistert von meinem Kauf der Kühlkammer bei der Firma Komplett Konzept. Die Kontaktaufnahme war äußerst unkompliziert und professionell. Das Team hat sich Zeit genommen, um alle meine Fragen zu beantworten und mir bei der Auswahl des richtigen Produkts zu helfen. Die Abwicklung war tadellos – alles wurde schnell und zuverlässig organisiert. Auch die Lieferung verlief ohne Probleme und innerhalb des angekündigten Zeitrahmens. Ich kann die Firma nur wärmstens empfehlen und werde bei Bedarf gerne wieder auf sie zurückkommen. Vielen Dank für den hervorragenden Service!',
    avatar: { bg: '#64748B', text: '#FFFFFF' },
  },
  {
    id: 'a-schneider',
    name: 'André Schneider',
    initials: 'A',
    when: 'vor einem Jahr',
    rating: 5,
    text: 'Das Team von Komplett Konzept hat uns an einem Sonntag unkompliziert und super schnell geholfen. Die Beratung war professionell und der Transport nach Rotterdam wurde auch am selben Tag schnellstens durchgeführt. Die Ware entsprach zu 100 Prozent der Beschreibung!',
    avatar: { bg: '#16A34A', text: '#FFFFFF' },
  },
  {
    id: 'schammuramat',
    name: 'schammuramat',
    initials: 'S',
    when: '',
    rating: 5,
    text: 'Qualität des Artikels ist gut! Keine Funktionseinschränkungen. Sehr nette Mitarbeiter! Sehr gerne wieder!',
    avatar: { bg: '#6D28D9', text: '#FFFFFF' },
  },
  {
    id: 'elmar1966',
    name: 'elmar1966',
    initials: 'E',
    when: '',
    rating: 5,
    text: 'Schnelle Lieferung, alles bestens, jederzeit gerne wieder !!!!!!!!!!!!!!!!!!!',
    avatar: { bg: '#64748B', text: '#FFFFFF' },
  },
  {
    id: 'dany-xx1',
    name: 'dany_xx1',
    initials: 'D',
    when: '',
    rating: 5,
    text: 'Schnelle Lieferung, gute Verpackung, alles wie beschrieben. Gerät funktioniert einwandfrei vielen Dank.',
    avatar: { bg: '#16A34A', text: '#FFFFFF' },
  },
  {
    id: 'handyman-9612',
    name: 'handyman_9612',
    initials: 'H',
    when: '',
    rating: 5,
    text: 'Arrived on time and in perfect condition.',
    avatar: { bg: '#0EA5E9', text: '#FFFFFF' },
  },
  {
    id: 'manta26',
    name: 'manta26',
    initials: 'M',
    when: '',
    rating: 5,
    text: 'Der Artikel wurde auf meinen Wunsch hin sehr schnell versendet. Leider hat das Gerät vermutlich während des Transports einen Schaden genommen. Der Kontakt mit dem Verkäufer war jedoch durchweg positiv – der Support hat sehr schnell reagiert, war konstruktiv und ist mir mit einer fairen Teilrückerstattung entgegengekommen. Ich hatte das Gefühl, dass dem Verkäufer die Kundenzufriedenheit wichtig ist und gehe daher von einem unglücklichen Einzelfall beim Versand aus. Vielen Dank noch mal!',
    avatar: { bg: '#F97316', text: '#111827' },
  },
  {
    id: 'volliwf',
    name: 'volliwf',
    initials: 'V',
    when: '',
    rating: 5,
    text: 'Sehr gute Qualität für Gebrauchteil.',
    avatar: { bg: '#15803D', text: '#FFFFFF' },
  },
];

export const getDefaultHomeReviewsContent = (): HomeReviewsContent => ({
  title: 'Kundenrezensionen',
  reviews: DEFAULT_HOME_REVIEWS.map((review) => ({ ...review, avatar: review.avatar ? { ...review.avatar } : undefined })),
});
