// https://nuxt.com/docs/api/configuration/nuxt-config
import { validateApiUrl } from './app/utils/pathHelper';
import cookieConfig from './app/configuration/cookie.config';
import { nuxtI18nOptions } from './app/configuration/i18n.config';
import { appConfiguration } from './app/configuration/app.config';
import { paths } from './app/utils/paths';
import { resolve } from 'pathe';

export default defineNuxtConfig({
  srcDir: 'app/',
  telemetry: false,
  devtools: { enabled: true },
  typescript: {
    typeCheck: true,
  },
  app: appConfiguration,
  experimental: {
    asyncContext: true,
  },
  appConfig: {
    titleSuffix: process.env.STORENAME || 'PlentyONE Shop',
    fallbackCurrency: 'GBP',
  },
  imports: {
    dirs: ['~/composables', '~/composables/**', '~/utils/**'],
  },
  vite: {
    server: {
      fs: {
        allow: ['../../..'], // relative to the current nuxt.config.ts
      },
      watch: {
        usePolling: process.env.NODE_ENV === 'development', // see apps/web/app/plugins/02.pwa-cookie.ts
      },
    },
    optimizeDeps: {
      include: [
        '@intlify/core-base',
        '@intlify/shared',
        '@paypal/paypal-js',
        '@plentymarkets/shop-api',
        '@plentymarkets/tailwind-colors',
        '@storefront-ui/shared',
        '@storefront-ui/vue',
        '@vee-validate/yup',
        '@vue/devtools-core',
        '@vue/devtools-kit',
        '@vueuse/core',
        '@vueuse/shared',
        'country-flag-icons/string/3x2',
        'dotenv',
        'drift-zoom',
        'js-sha256',
        'swiper/modules',
        'swiper/vue',
        'uuid',
        'validator',
        'vue-multiselect',
        'vue3-lazy-hydration',
        'vue-tel-input',
        'vuedraggable/src/vuedraggable',
        'yup',
      ],
    },
    build: {
      rollupOptions: {
        output: {
          manualChunks: {
            vuetify: ['vuetify', '@fortawesome/fontawesome-free'],
          },
        },
      },
    },
  },
  css: ['~/assets/style.scss'],
  // TODO: build is consistently failing because of this. check whether we need pre-render check.
  nitro: {
    prerender: {
      crawlLinks: false,
    },
    compressPublicAssets: true,
  },
  routeRules: {
    '/_ipx/**': { headers: { 'cache-control': `public, max-age=31536000, immutable` } },
    '/_nuxt-plenty/icons/**': { headers: { 'cache-control': `public, max-age=31536000, immutable` } },
    '/_nuxt-plenty/favicon.ico': { headers: { 'cache-control': `public, max-age=31536000, immutable` } },
    '/_nuxt-plenty/images/**': { headers: { 'cache-control': `max-age=604800` } },
  },
  image: {
    provider: 'none',
  },
  site: {
    url: '',
  },
  pages: true,
  runtimeConfig: {
    public: {
      domain: validateApiUrl(process.env.API_URL) ?? process.env.API_ENDPOINT,
      apiEndpoint: process.env.API_ENDPOINT,
      isDev: process.env.NODE_ENV === 'development',
      activeLanguages: process.env.LANGUAGELIST || 'en,de',
      enableCategoryEditing: process.env.NODE_ENV === 'development' || process.env?.ENABLE_CATEGORY_EDITING === '1',
      enableProductEditing: process.env?.ENABLE_PRODUCT_EDITING === '1',
      enableAllEditorSettings:
        process.env.NODE_ENV === 'development' || process.env?.ENABLE_ALL_EDITOR_SETTINGS === '1',
      editorSettingsDevFlag:
        process.env.NODE_ENV === 'development' || process.env?.ENABLE_ALL_EDITOR_SETTINGS === '1'
          ? []
          : [
              'autogenerated-pages',
              'other-robots-settings',
              'robots-meta-tag-for-item-pages',
              'search-engines',
              'tracking-and-analytics',
              'customer-management',
              'variation-position-based-on-sales',
              'security',
              'item-internal-sorting',
              'contact-form',
              'default-B2B-customer-class',
              'default-B2C-and-guest-customer-class',
              'session-and-url-lifetime',
              'availability',
              'item-condition',
              'rich-snippet-mapping',
              'google-analytics',
            ],
      cookieGroups: cookieConfig,
      turnstileSiteKey: process.env?.CLOUDFLARETURNSTILEAPISITEKEY ?? '',
      useAvif: process.env?.IMAGEAVIF === 'true' || process.env?.NUXT_PUBLIC_USE_AVIF === 'true',
      useWebp: process.env?.IMAGEWEBP === 'true' || process.env?.NUXT_PUBLIC_USE_WEBP === 'true',
      validateReturnReasons: process.env.VALIDATE_RETURN_REASONS === '1',
      enableQuickCheckoutTimer: process.env.ENABLE_QUICK_CHECKOUT_TIMER === '1',
      useTagsOnCategoryPage: process.env.USE_TAGS_ON_CATEGORY_PAGE === '1',
      isPreview: false,
      showConfigurationDrawer: process.env.SHOW_CONFIGURATION_DRAWER === '1',
      defaultItemsPerPage: Number(process.env.DEFAULT_FEEDBACK_ITEMS_PER_PAGE ?? 10),
      favicon: process.env.NUXT_PUBLIC_FAVICON || '/_nuxt-plenty/favicon.ico',
      ogTitle: process.env.NUXT_PUBLIC_OG_TITLE || process.env.OG_TITLE || 'PlentyONE Shop',
      ogImg: process.env.NUXT_PUBLIC_OG_IMG || process.env.OG_IMG || '/_nuxt-plenty/images/logo.svg',
      ogType: process.env.NUXT_PUBLIC_OG_TYPE || process.env.OG_TYPE || 'website',
      metaTitle: process.env.NUXT_PUBLIC_META_TITLE || process.env.METATITLE || 'PlentyONE Shop',
      metaDescription:
        process.env.NUXT_PUBLIC_META_DESCRIPTION || process.env.METADESC || 'Demo shop for PlentyONE Shop',
      metaKeywords: process.env.NUXT_PUBLIC_META_KEYWORDS || process.env.METAKEYWORDS || 'PlentyONE, plentyshop, pwa',
      robots: process.env.NUXT_PUBLIC_ROBOTS || 'all',
      contactShopEmail: process.env.NUXT_PUBLIC_CONTACT_SHOP_EMAIL || 'your@email.com',
      robotsHomePage: process.env.NUXT_PUBLIC_ROBOTS_HOME_PAGE || 'all',
      robotsContactPage: process.env.NUXT_PUBLIC_ROBOTS_CONTACT_PAGE || 'all',
      robotsCancellationRights: process.env.NUXT_PUBLIC_ROBOTS_CANCELLATION_RIGHTS || 'all',
      robotsCancellationForm: process.env.NUXT_PUBLIC_ROBOTS_CANCELLATION_FORM || 'all',
      robotsLegalDisclosure: process.env.NUXT_PUBLIC_ROBOTS_LEGAL_DISCOLSURE || 'all',
      robotsPrivacyPolicy: process.env.NUXT_PUBLIC_ROBOTS_PRIVACY_POLICY || 'all',
      robotsTermsAndConditions: process.env.NUXT_PUBLIC_ROBOTS_TERMS_AND_CONDITIONS || 'all',
      robotsSearchResult: process.env.NUXT_PUBLIC_SEARCH_RESULT || 'all',
      robotsAccessibilityDeclaration: process.env.NUXT_PUBLIC_ROBOTS_ACCESSIBILITY_DECLARATION || 'all',
      robotsStopIndexing: process.env.NUXT_PUBLIC_ROBOTS_STOP_INDEXING || '0',
      robotsItemPage: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || 'ALL',
      robotsItemPageId: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || '1',
      itemCanonicalId: process.env.NUXT_PUBLIC_ITEM_CANONICAL_ID || '',
      seoRichSnippetBrand: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || '1',
      seoRichSnippetBrandId: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || '',
      seoRichSnippetManufacturer: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || '1',
      seoRichSnippetBarcodeGtin: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN || '1',
      seoRichSnippetBarcodeGtinId: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN_ID || '',
      seoRichSnippetBarcodeGtin8: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN8 || '1',
      seoRichSnippetBarcodeGtin8Id: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN8_ID || '',
      seoRichSnippetBarcodeGtin13: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN13 || '1',
      seoRichSnippetBarcodeGtin13Id: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN13_ID || '',
      seoRichSnippetBarcodeIsbn: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_ISBN || '1',
      seoRichSnippetBarcodeIsbnId: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_ISBN_ID || '',
      seoRichSnippetMpnBarcode: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_MPN_BARCODE || '1',
      seoRichSnippetMpnBarcodeId: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_MPN_BARCODE_ID || '',
      seoRichSnippetIdForPriceValidity: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_PRICE_VALIDITY || '1',
      seoRichSnippetSkuBarcode: process.env.NUXT_PUBLIC_SEO_RICH_SKU_BARCODE || '1',
      seoRichSnippetSkuBarcodeId: process.env.NUXT_PUBLIC_SEO_RICH_SKU_BARCODE_ID || '',
      robotsUrlWithParameters: process.env.NUXT_PUBLIC_ROBOTS_URL_WITH_PARAMETERS || 'false',
      itemConditionNew: process.env.NUXT_PUBLIC_ITEM_CONDITION_NEW || '',
      itemConditionUsed: process.env.NUXT_PUBLIC_ITEM_CONDITION_USED || '',
      itemConditionNewBox: process.env.NUXT_PUBLIC_ITEM_CONDITION_NEW_BOX || '',
      itemConditionNewLabel: process.env.NUXT_PUBLIC_ITEM_CONDITION_NEW_LABEL || '',
      itemConditionBStock: process.env.NUXT_PUBLIC_ITEM_CONDITION_B_STOCK || '',
      seoAvailability1: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY1 || '',
      seoAvailability2: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY2 || '',
      seoAvailability3: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY3 || '',
      seoAvailability4: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY4 || '',
      seoAvailability5: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY5 || '',
      seoAvailability6: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY6 || '',
      seoAvailability7: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY7 || '',
      seoAvailability8: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY8 || '',
      seoAvailability9: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY9 || '',
      seoAvailability10: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY10 || '',
      enableGoogleAnalytics: process.env.NUXT_PUBLIC_ENABLE_GOOGLE_ANALITICS || 'false',
      googleAnalyticsTrakingId: process.env.NUXT_PUBLIC_GOOGLE_ANALITICS_TRACKING_ID || '',
      sendGrossPricesToGoogleAnalytics: process.env.NUXT_PUBLIC_SEND_GROSS_PRICES_TO_GOOGLE_ANALITICS || 'false',
      googleAnalyticsCookieGroup: process.env.NUXT_PUBLIC_GOOGLE_ANALITICS_COOKIE_GROUP || 'CookieBar.marketing.label',
      registerCookieAsOptOut: process.env.NUXT_PUBLIC_REGISTER_COOKIE_AS_OPT_OUT || 'false',
      manufacturerExternalName: process.env.NUXT_PUBLIC_MANUFACTURER_EXTERNAL_NAME || '0',
      manufacturerName: process.env.NUXT_PUBLIC_MANUFACTURER_NAME || '0',
      sortingDynamicInherit: process.env.NUXT_PUBLIC_SORTING_DINAMIC_INHERIT || '[]',
      sortingDynamicPrio1: process.env.NUXT_PUBLIC_SORTING_DYNAMIC_PRIO1 || 'filter.prices.price_asc',
      sortingDynamicPrio2: process.env.NUXT_PUBLIC_SORTING_DYNAMIC_PRIO2 || 'filter.prices.price_asc',
      themeColor: process.env.NUXT_PUBLIC_PRIMARY_COLOR || '#062633',
      headerLogo:
        process.env.NUXT_PUBLIC_HEADER_LOGO ||
        process.env.LOGO ||
        'https://cdn02.plentymarkets.com/mevofvd5omld/frontend/Logo/logo.svg',
      homepageCategoryId: Number(process.env.HOMEPAGE) ?? null,
      shippingTextCategoryId: Number(process.env.SHIPPINGTEXT) ?? null,
      storename: process.env.STORENAME || 'PlentyONE GmbH',
      noCache: process.env.NO_CACHE || '',
      configId: process.env.CONFIG_ID || '',
      isHero: true,
      font: process.env.NUXT_PUBLIC_FONT || 'Red Hat Text',
      blockSize: process.env.NUXT_PUBLIC_BLOCK_SIZE || 'm',
      primaryColor: process.env.NUXT_PUBLIC_PRIMARY_COLOR || '#062633',
      defaultSortingOption: process.env.NUXT_PUBLIC_DEFAULT_SORTING_OPTION ?? 'texts.name1_asc',
      defaultSortingSearch: process.env.NUXT_PUBLIC_DEFAULT_SORTING_SEARCH ?? 'item.score',
      availableSortingOptions:
        process.env.NUXT_PUBLIC_AVAILABLE_SORTING_OPTIONS ||
        '["item.score","texts.name1_asc","default.recommended_sorting","sorting.price.avg_asc","sorting.price.avg_desc","variation.availability.averageDays_asc","variation.availability.averageDays_desc"]',
      recommendedFirstSortingOption:
        process.env.NUXT_PUBLIC_RECOMMENDED_FIRST_SORTING_OPTION ?? 'variation.position_desc',
      recommendedSecondSortingOption:
        process.env.NUXT_PUBLIC_RECOMMENDED_SECOND_SORTING_OPTION ?? 'sorting.price.avg_asc',
      recommendedThirdSortingOption:
        process.env.NUXT_PUBLIC_RECOMMENDED_THIRD_SORTING_OPTION ?? 'variation.availability.averageDays_asc',
      secondaryColor: process.env.NUXT_PUBLIC_SECONDARY_COLOR || '#31687d',
      headerBackgroundColor:
        process.env.NUXT_PUBLIC_HEADER_BACKGROUND_COLOR || process.env.NUXT_PUBLIC_PRIMARY_COLOR || '#062633',
      iconColor: process.env.NUXT_PUBLIC_ICON_COLOR || '#ffffff',
      showCustomerWishComponent: process.env.NUXT_PUBLIC_SHOW_CUSTOMER_WISH_COMPONENT === 'true',
      showCustomerReferenceComponent: process.env.NUXT_PUBLIC_SHOW_CUSTOMER_REFERENCE_COMPONENT === 'true',
      bundleItemDisplay: process.env.NUXT_PUBLIC_BUNDLE_ITEM_DISPLAY || '2',
      externalVatCheckInactive: process.env.NUXT_PUBLIC_EXTERNAL_VAT_CHECK_INACTIVE === 'true',
      itemSortByMonthlySales: process.env.NUXT_PUBLIC_ITEM_SORT_BY_MONTHLY_SALES || '0',
      defaultCustomerClassId: process.env.NUXT_PUBLIC_DEFAULT_CUSTOMER_CLASS_ID || '0',
      defaultB2BCustomerClass: process.env.NUXT_PUBLIC_DEFAULT_B2B_CUSTOMER_CLASS || '0',
      fetchDynamicTranslations: false,
      sessionLifetime: process.env.NUXT_PUBLIC_SESSION_LIFETIME || '3600',
    },
  },
  modules: [
    '@plentymarkets/shop-core',
    '@plentymarkets/shop-module-mollie',
    '@plentymarkets/shop-module-gtag',
    '@nuxt/eslint',
    '@nuxt/fonts',
    '@nuxt/image',
    '@nuxt/test-utils/module',
    '@nuxtjs/i18n',
    '@nuxtjs/sitemap',
    '@nuxtjs/tailwindcss',
    '@nuxtjs/turnstile',
    'nuxt-lazy-hydrate',
    'nuxt-viewport',
    '@vee-validate/nuxt',
    '@vite-pwa/nuxt',
    'vuetify-nuxt-module',
  ],
  vuetify: {
    moduleOptions: {
      disableVuetifyStyles: true,
    },
    vuetifyOptions: {
      icons: {
        defaultSet: 'fa',
      },
    },
  },
  shopCore: {
    apiUrl: validateApiUrl(process.env.API_URL) ?? 'http://localhost:8181',
  },
  shopModuleMollie: {
    checkoutUrl: paths.checkout,
    liveMode: !process.env.MOLLIE_TEST_MODE,
    confirmationUrl: paths.confirmation,
  },
  fonts: {
    defaults: {
      weights: [300, 400, 500, 700],
    },
    assets: {
      prefix: '/_nuxt-plenty/fonts/',
    },
  },
  i18n: nuxtI18nOptions,
  sitemap: {
    autoLastmod: true,
    xsl: '/sitemap_style.xsl',
    xslColumns: [
      // URL column must always be set, no value needed
      { label: 'URL', width: '75%' },
      { label: 'Last Modified', select: 'sitemap:lastmod', width: '25%' },
    ],
    sitemaps: {
      'sitemap/content': {
        exclude: [
          `/${nuxtI18nOptions.defaultLocale}/**`,
          '/search',
          '/offline',
          '/my-account/**',
          '/readonly-checkout',
          '/set-new-password',
          '/reset-password-success',
          '/cart',
          '/checkout',
          '/confirmation',
          '/wishlist',
          '/login',
          '/signup',
          '/reset-password',
        ],
        includeAppSources: true,
      },
    },
  },
  tailwindcss: {
    configPath: '~/configuration/tailwind.config.ts',
    exposeConfig: true,
  },
  viewport: {
    breakpoints: {
      xs: 380,
      sm: 640,
      md: 768,
      lg: 1024,
      '4xl': 1920,
    },
    defaultBreakpoints: {
      mobile: 'sm',
      tablet: 'md',
      desktop: 'lg',
      wideScreen: '4xl',
    },
    fallbackBreakpoint: 'lg',
    cookie: {
      expires: 365,
      name: 'plenty-viewport',
      path: '/',
      sameSite: 'Strict',
      secure: true,
    },
  },
  veeValidate: {
    autoImports: false,
    componentNames: {
      Form: 'VeeForm',
      Field: 'VeeField',
      FieldArray: 'VeeFieldArray',
      ErrorMessage: 'VeeErrorMessage',
    },
  },
  pwa: {
    registerType: 'prompt',
    workbox: {
      navigateFallback: null,
      globPatterns: ['**/*.{js,json,css,html,ico,svg,png,webp,ico,woff,woff2,ttf,eit,otf}', '_nuxt-plenty/icons/*'],
      globIgnores: ['manifest**.webmanifest'],
      additionalManifestEntries: [
        {
          url: '/offline',
          revision: Math.random().toString(32),
        },
      ],
      navigationPreload: true,
      runtimeCaching: [
        {
          urlPattern: ({ request }) => request.mode === 'navigate',
          handler: 'NetworkFirst',
          options: {
            precacheFallback: {
              fallbackURL: '/offline',
            },
          },
        },
        {
          urlPattern: ({ request }) => request.destination === 'image',
          handler: 'NetworkFirst',
          options: {
            cacheName: 'plenty-image-cache',
            expiration: {
              maxEntries: 300,
              maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
            },
            cacheableResponse: {
              statuses: [0, 200],
            },
          },
        },
        {
          urlPattern: /^https:\/\/fonts\.googleapis\.com\/.*/i,
          handler: 'NetworkFirst',
          options: {
            cacheName: 'google-fonts-cache',
            expiration: {
              maxEntries: 10,
              maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
            },
            cacheableResponse: {
              statuses: [0, 200],
            },
          },
        },
        {
          urlPattern: /^https:\/\/fonts\.gstatic\.com\/.*/i,
          handler: 'NetworkFirst',
          options: {
            cacheName: 'gstatic-fonts-cache',
            expiration: {
              maxEntries: 10,
              maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
            },
            cacheableResponse: {
              statuses: [0, 200],
            },
          },
        },
      ],
      cleanupOutdatedCaches: true,
    },
    manifest: {
      name: process.env.NUXT_PUBLIC_OG_TITLE || process.env.OG_TITLE || 'PlentyONE Shop',
      short_name: process.env.NUXT_PUBLIC_OG_TITLE || process.env.OG_TITLE || 'PlentyONE Shop',
      description: process.env.NUXT_PUBLIC_META_DESCRIPTION || process.env.METADESC || 'PlentyONE Shop',
      theme_color: process.env.NUXT_PUBLIC_PRIMARY_COLOR || '#062633',
      background_color: '#ffffff',
      display: 'standalone',
      start_url: '/',
      scope: '/',
      icons: [
        {
          src: '/_nuxt-plenty/icons/icon-192x192.png',
          sizes: '192x192',
          type: 'image/png',
        },
        {
          src: '/_nuxt-plenty/icons/icon-512x512.png',
          sizes: '512x512',
          type: 'image/png',
        },
        {
          src: '/_nuxt-plenty/icons/icon-512x512.maskable.png',
          sizes: '512x512',
          type: 'image/png',
          purpose: 'maskable',
        },
      ],
    },
    registerWebManifestInRouteRules: true,
  },
  hooks: {
    'pages:extend'(pages) {
      if (process.env.E2E_TEST) {
        pages.push({
          name: 'e2e',
          path: '/smoke-e2e',
          file: resolve(__dirname, 'e2e/smoke-e2e.vue'),
        });
      }
    },
  },
});
