export const products = [
  {
    variation: {
      id: 1,
      name: 'Var 1',
      availabilityId: 1,
      minimumOrderQuantity: 1,
      mayShowUnitPrice: false,
      vatId: 1,
      availability: {
        id: 1,
        icon: '',
        averageDays: 0,
        createdAt: '',
        updatedAt: '',
        names: { id: 1, availabilityId: 1, lang: 'en', name: 'Available', createdAt: '', updatedAt: '' },
      },
      availabilityUpdatedAt: '',
    },
    texts: { name1: 'Product 1', name2: '', name3: '', urlPath: '', lang: 'en' },
    unit: { unitOfMeasurement: 'pcs', names: { unitId: 1, lang: 'en', name: 'Piece' }, content: 1 },
    item: {
      id: 1,
      condition: { names: { name: 'New', lang: 'en' } },
      manufacturerId: 1,
      itemType: 'default',
      manufacturer: { externalName: 'Brand', name: 'Brand' },
    },
    images: { all: [], variation: [] },
    filter: { isSalable: true, isSalableAndActive: true },
    properties: [],
    facets: [],
  },
  {
    variation: {
      id: 2,
      name: 'Var 2',
      availabilityId: 1,
      minimumOrderQuantity: 1,
      mayShowUnitPrice: false,
      vatId: 1,
      availability: {
        id: 1,
        icon: '',
        averageDays: 0,
        createdAt: '',
        updatedAt: '',
        names: { id: 1, availabilityId: 1, lang: 'en', name: 'Available', createdAt: '', updatedAt: '' },
      },
      availabilityUpdatedAt: '',
    },
    texts: { name1: 'Product 2', name2: '', name3: '', urlPath: '', lang: 'en' },
    unit: { unitOfMeasurement: 'pcs', names: { unitId: 1, lang: 'en', name: 'Piece' }, content: 1 },
    item: {
      id: 2,
      condition: { names: { name: 'New', lang: 'en' } },
      manufacturerId: 1,
      itemType: 'default',
      manufacturer: { externalName: 'Brand', name: 'Brand' },
    },
    images: { all: [], variation: [] },
    filter: { isSalable: true, isSalableAndActive: true },
    properties: [],
    facets: [],
  },
];
