nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.3.cjs

npmScopes:
  plentymarkets:
    npmRegistryServer: 'https://npm.pkg.github.com'
    npmAuthToken: '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'
