export const fakeProductDE = {
  images: {
    all: [
      {
        names: {
          name: '',
          lang: 'de',
          imageId: 23,
          alternate: '',
        },
        url: '/_nuxt-plenty/images/productPlaceholder.png',
        urlPreview: '/_nuxt-plenty/images/productPlaceholder.png',
        urlSecondPreview: '',
        urlMiddle: '/_nuxt-plenty/images/productPlaceholder.png',
        position: 0,
        path: 'S3:109:109-Barhocker-White-SanFrancisco.jpg',
        cleanImageName: '109-Barhocker-White-SanFrancisco.jpg',
      },
    ],
    variation: [],
  },
  item: {
    id: 109,
    storeSpecial: null,
    manufacturerId: 2,
    itemType: 'default',
    manufacturer: {
      position: 0,
      externalName: 'A & C Design',
    },
    rebate: 0,
    salableVariationCount: 1,
    customsTariffNumber: '',
    producingCountry: {
      names: [],
    },
    condition: {
      names: [],
    },
  },
  texts: {
    urlPath: 'wohnzimmer/sessel-hocker/barhocker-white-sanfrancisco',
    technicalData:
      'Das Feld „Technische Daten“ ermöglicht es Ihnen, zusätzliche detaillierte Informationen zu einem Produkt bereitzustellen. Es bietet die gleichen Formatierungsoptionen wie das Artikeltext-Feld.</br>Neben technischen Daten können Sie dieses Feld auch für andere Produktinformationen nutzen, die Sie gesondert hervorheben möchten, z. B.:<ul><li>Pflegehinweise bei Kleidung</li><li>Zutaten oder Nährwertangaben bei Lebensmitteln</li><li>Maße bei Möbeln</li><li>Weitere relevante Produktdetails</li></ul>',
    name3: 'Name 3 EN',
    title: 'HTML-Titel für Webshop DE',
    itemId: 128,
    id: 104,
    lang: 'de',
    description:
      "<p>Auf dieser Seite können Sie festlegen, wie Ihre Produktdetailseiten gestaltet werden sollen. Sie bestimmen selbst, welche Inhalte sichtbar sind, in welcher Reihenfolge diese erscheinen und wie umfangreich die Informationen sein sollen. Um die Bearbeitung zu starten, bewegen Sie die Maus über ein Element und<span style='color: purple'>klicken Sie auf den lilafarbenen Stift.</span></p>Das Feld, das Sie hier gerade sehen, ist der <span style='font-weight: bold'>Artikeltext</span>. Hierbei handelt es sich um einen Fließtext, der beliebig lang sein darf. Nutzen Sie diesen Platz, um Ihren Kundinnen und Kunden ausführliche Informationen zu Ihrem Produkt bereitzustellen, zum Beispiel besondere Merkmale oder Einsatzmöglichkeiten</br></br>Der Text, den Sie aktuell sehen, ist selbstverständlich nur ein Platzhaltertext. Er dient dazu, Ihnen zu veranschaulichen, an welcher Stelle die Produktbeschreibung auf der Produktdetailseite angezeigt wird und wie diese optisch eingebettet ist.</br></br>Die eigentlichen Artikeltexte verwalten Sie im Backend in der Artikelverwaltung. Dort stehen Ihnen zahlreiche Formatierungsmöglichkeiten zur Verfügung, mit denen Sie Ihre Inhalte ansprechend gestalten können, zum Beispiel:<ul><li>Einfügen von Links</li><li>Integration von kleinen Bildern oder Icons</li><li>Erstellen übersichtlicher Tabellen</li><li>Verwendung von Absätzen und Listen zur besseren Strukturierung</li><li>und vieles mehr.</li></ul></br>Nutzen Sie diese Funktionen, um Ihre Produktseiten individuell zu gestalten und ein überzeugendes Einkaufserlebnis zu schaffen.",
    metaDescription: 'Meta Description DE',
    name2: 'Beispielprodukt DE',
    name1: 'Beispielprodukt',
    shortDescription: 'Hochwertige Businesstasche aus feinstem Leder: Eleganz trifft auf Funktionalität. Dies ist der Vorschautext (DE).',
    keywords: 'Meta-Keywords DE',
  },
  variation: {
    itemId: 109,
    availabilityId: 1,
    maximumOrderQuantity: null,
    minimumOrderQuantity: 1,
    intervalOrderQuantity: 1,
    releasedAt: null,
    name: '',
    vatId: 0,
    bundleType: null,
    mayShowUnitPrice: true,
    availability: {
      id: 1,
      icon: 'av1.gif',
      averageDays: 2,
      createdAt: '2022-06-27 09:20:16',
      updatedAt: '2022-06-27 09:20:16',
      names: {
        id: 41,
        availabilityId: 1,
        lang: 'de',
        name: 'Sofort versandfertig, Lieferzeit 48h',
        createdAt: '2022-06-27 09:20:16',
        updatedAt: '2022-06-27 09:20:16',
      },
    },
    id: 1007,
    availabilityUpdatedAt: '2018-02-28T11:49:53+01:00',
    model: '',
  },
  filter: {
    isSalable: true,
    isSalableAndActive: true,
    hasActiveChildren: false,
    hasChildren: true,
  },
  unit: {
    names: {
      unitId: 1,
      lang: 'de',
      name: 'Stück',
    },
    unitOfMeasurement: 'C62',
    content: 1,
  },
  properties: [],
  hasOrderProperties: false,
  hasRequiredOrderProperty: false,
  groupedAttributes: [],
  prices: {
    default: {
      price: {
        value: 110,
        formatted: '110,00 EUR',
      },
      unitPrice: {
        value: 110,
        formatted: '110,00 EUR',
      },
      basePrice: '110,00 EUR / Stück',
      baseLot: 1,
      baseUnit: 'C62',
      baseSinglePrice: 110,
      minimumOrderQuantity: 1,
      contactClassDiscount: {
        percent: 0,
        amount: 0,
      },
      categoryDiscount: {
        percent: 0,
        amount: 0,
      },
      currency: 'EUR',
      lowestPrice: {
        value: null,
        formatted: '',
      },
      vat: {
        id: 0,
        value: 19,
      },
      isNet: false,
      data: {
        salesPriceId: 1,
        price: 110,
        priceNet: 92.436974789916,
        basePrice: 110,
        basePriceNet: 92.436974789916,
        unitPrice: 110,
        unitPriceNet: 92.436974789916,
        lowestPrice: null,
        lowestPriceNet: null,
        customerClassDiscountPercent: 0,
        customerClassDiscount: 0,
        customerClassDiscountNet: 0,
        categoryDiscountPercent: 0,
        categoryDiscount: 0,
        categoryDiscountNet: 0,
        vatId: 0,
        vatValue: 19,
        currency: 'EUR',
        interval: 'none',
        conversionFactor: 1,
        minimumOrderQuantity: '1.00',
        updatedAt: '2022-03-18 10:29:04',
        type: 'default',
        pricePosition: 0,
      },
    },
    rrp: {
      price: {
        value: 110,
        formatted: '110,00 EUR',
      },
      unitPrice: {
        value: 110,
        formatted: '110,00 EUR',
      },
      basePrice: '110,00 EUR / Stück',
      baseLot: 1,
      baseUnit: 'C62',
      baseSinglePrice: 150,
      minimumOrderQuantity: 0,
      contactClassDiscount: {
        percent: 0,
        amount: 0,
      },
      categoryDiscount: {
        percent: 0,
        amount: 0,
      },
      currency: 'EUR',
      lowestPrice: {
        value: null,
        formatted: '',
      },
      vat: {
        id: 0,
        value: 19,
      },
      isNet: false,
      data: {
        salesPriceId: 2,
        price: 150,
        priceNet: 126.05042016807,
        basePrice: 150,
        basePriceNet: 126.05042016807,
        unitPrice: 150,
        unitPriceNet: 126.05042016807,
        lowestPrice: null,
        lowestPriceNet: null,
        customerClassDiscountPercent: 0,
        customerClassDiscount: 0,
        customerClassDiscountNet: 0,
        categoryDiscountPercent: 0,
        categoryDiscount: 0,
        categoryDiscountNet: 0,
        vatId: 0,
        vatValue: 19,
        currency: 'EUR',
        interval: 'none',
        conversionFactor: 1,
        minimumOrderQuantity: '0.00',
        updatedAt: '2022-03-18 10:29:04',
        type: 'rrp',
        pricePosition: 0,
      },
    },
    set: null,
    specialOffer: null,
    graduatedPrices: [],
  },
  facets: [],
  attributes: [],
};
