export const variationPropertiesDE = [
  {
    id: 3,
    position: 1,
    name: null,
    description: null,
    properties: [
      {
        cast: 'text',
        referrer: [1, 162],
        names: {
          id: 15,
          propertyId: 9,
          lang: 'de',
          name: '(Eigenschaft) Beispiel: Beispiel 1',
          description: 'As Text Property',
          createdAt: '2025-09-22 19:01:56',
          updatedAt: '2025-09-22 19:03:13',
        },
        clients: [70016],
        display: ['showOnItemsPage', 'groupIsHidden'],
        groups: [
          {
            id: 3,
            position: 1,
            createdAt: '2025-03-28 10:36:56',
            updatedAt: '2025-03-28 10:36:56',
            options: [],
          },
        ],
        id: 9,
        groupId: 3,
        position: 30,
        markup: 0,
        values: {
          id: 37,
          lang: 'de',
          value: 'Glass (Bottle), Cap (Metal)',
          description: '',
        },
      },
    ],
  },
  {
    id: 1,
    position: 1,
    name: 'no group (automatically generated)',
    description: '',
    properties: [
      {
        cast: 'selection',
        referrer: [1, 162],
        names: {
          id: 9,
          propertyId: 5,
          lang: 'de',
          name: 'Color',
          description: '',
          createdAt: '2025-09-22 10:41:42',
          updatedAt: '2025-09-22 10:41:42',
        },
        clients: [70016],
        display: ['showInItemListing', 'showOnItemsPage', 'groupIsHidden'],
        options: [],
        groups: [
          {
            id: 1,
            position: 1,
            createdAt: '2021-07-15 12:23:32',
            updatedAt: '2021-07-15 12:23:32',
            options: [
              {
                id: 1,
                groupId: 1,
                type: 'groupType',
                value: 'none',
                createdAt: '2021-07-15 12:23:32',
                updatedAt: '2021-07-15 12:23:32',
              },
              {
                id: 2,
                groupId: 1,
                type: 'surchargeType',
                value: 'flat',
                createdAt: '2021-07-15 12:23:32',
                updatedAt: '2021-07-15 12:23:32',
              },
            ],
          },
        ],
        id: 5,
        groupId: 1,
        position: 0,
        markup: 0,
        values: {
          selectionId: 1,
          lang: 'de',
          value: 'Copper',
          description: '',
          position: 1,
        },
      },
      {
        cast: 'selection',
        referrer: [1, 162],
        names: {
          id: 11,
          propertyId: 6,
          lang: 'de',
          name: 'Material',
          description: '',
          createdAt: '2025-09-22 10:45:39',
          updatedAt: '2025-09-22 10:45:39',
        },
        clients: [70016],
        display: ['groupIsHidden', 'showInItemListing', 'showOnItemsPage'],
        options: [],
        groups: [
          {
            id: 1,
            position: 1,
            createdAt: '2021-07-15 12:23:32',
            updatedAt: '2021-07-15 12:23:32',
            options: [
              {
                id: 1,
                groupId: 1,
                type: 'groupType',
                value: 'none',
                createdAt: '2021-07-15 12:23:32',
                updatedAt: '2021-07-15 12:23:32',
              },
              {
                id: 2,
                groupId: 1,
                type: 'surchargeType',
                value: 'flat',
                createdAt: '2021-07-15 12:23:32',
                updatedAt: '2021-07-15 12:23:32',
              },
            ],
          },
        ],
        id: 6,
        groupId: 1,
        position: 20,
        markup: 0,
        values: {
          selectionId: 14,
          lang: 'de',
          value: '(Eigenschaft) Beispiel: Beispiel 1',
          description: '',
          position: 20,
        },
      },
      {
        cast: 'text',
        referrer: [1, 162],
        names: [],
        clients: [70016],
        display: ['showOnItemsPage'],
        options: [],
        groups: [
          {
            id: 1,
            position: 1,
            createdAt: '2021-07-15 12:23:32',
            updatedAt: '2021-07-15 12:23:32',
            names: {
              id: 2,
              groupId: 1,
              lang: 'de',
              name: 'no group (automatically generated)',
              description: '',
              createdAt: '2021-07-15 12:23:32',
              updatedAt: '2021-07-15 12:23:32',
            },
            options: [
              {
                id: 1,
                groupId: 1,
                type: 'groupType',
                value: 'none',
                createdAt: '2021-07-15 12:23:32',
                updatedAt: '2021-07-15 12:23:32',
              },
              {
                id: 2,
                groupId: 1,
                type: 'surchargeType',
                value: 'flat',
                createdAt: '2021-07-15 12:23:32',
                updatedAt: '2021-07-15 12:23:32',
              },
            ],
          },
        ],
        id: 7,
        groupId: 1,
        position: 1000,
        markup: 0,
        values: {
          id: 39,
          lang: 'de',
          value: '(Eigenschaft) Beispiel: Beispiel 2',
          description: '',
        },
      },
    ],
  },
];
