import cookieConfig from './cookie.config';
import { validateApiUrl } from '../utils/pathHelper';

export default {
  domain: validateApiUrl(process.env.API_URL) ?? process.env.API_ENDPOINT,
  apiEndpoint: process.env.API_ENDPOINT,
  activeLanguages: process.env.LANGUAGELIST || 'en,de',
  disabledEditorSettings: process.env?.ENABLE_ALL_EDITOR_SETTINGS === '1' ? [] : ['shop-search'],
  cookieGroups: cookieConfig,
  turnstileSiteKey: process.env?.CLOUDFLARETURNSTILEAPISITEKEY ?? '',
  useAvif: process.env?.IMAGEAVIF === 'true' || process.env?.NUXT_PUBLIC_USE_AVIF === 'true',
  useWebp: process.env?.IMAGEWEBP === 'true' || process.env?.NUXT_PUBLIC_USE_WEBP === 'true',
  validateReturnReasons: process.env.VALIDATE_RETURN_REASONS === '1',
  enableQuickCheckoutTimer: process.env.ENABLE_QUICK_CHECKOUT_TIMER === '1',
  useTagsOnCategoryPage: process.env.USE_TAGS_ON_CATEGORY_PAGE === '1',
  isPreview: false,
  showConfigurationDrawer: process.env.SHOW_CONFIGURATION_DRAWER === '1',
  defaultItemsPerPage: Number(process.env.DEFAULT_FEEDBACK_ITEMS_PER_PAGE ?? 10),
  favicon: process.env.NUXT_PUBLIC_FAVICON || '/_nuxt-plenty/favicon.ico',
  ogTitle: process.env.NUXT_PUBLIC_OG_TITLE || process.env.OG_TITLE || 'PlentyONE Shop',
  ogImg: process.env.NUXT_PUBLIC_OG_IMG || process.env.OG_IMG || '/_nuxt-plenty/images/logo.svg',
  ogType: process.env.NUXT_PUBLIC_OG_TYPE || process.env.OG_TYPE || 'website',
  metaTitle: process.env.NUXT_PUBLIC_META_TITLE || process.env.METATITLE || 'PlentyONE Shop',
  metaDescription: process.env.NUXT_PUBLIC_META_DESCRIPTION || process.env.METADESC || 'Demo shop for PlentyONE Shop',
  metaKeywords: process.env.NUXT_PUBLIC_META_KEYWORDS || process.env.METAKEYWORDS || 'PlentyONE, plentyshop, pwa',
  passwordMinLength: Number(process.env.PASSWORD_MIN_LENGTH ?? 8),
  passwordMaxLength: Number(process.env.PASSWORD_MAX_LENGTH ?? 64),
  robots: process.env.NUXT_PUBLIC_ROBOTS || 'all',
  contactShopEmail: process.env.NUXT_PUBLIC_CONTACT_SHOP_EMAIL || 'your@email.com',
  robotsHomePage: process.env.NUXT_PUBLIC_ROBOTS_HOME_PAGE || 'all',
  robotsContactPage: process.env.NUXT_PUBLIC_ROBOTS_CONTACT_PAGE || 'all',
  robotsCancellationRights: process.env.NUXT_PUBLIC_ROBOTS_CANCELLATION_RIGHTS || 'all',
  robotsCancellationForm: process.env.NUXT_PUBLIC_ROBOTS_CANCELLATION_FORM || 'all',
  robotsLegalDisclosure: process.env.NUXT_PUBLIC_ROBOTS_LEGAL_DISCOLSURE || 'all',
  robotsPrivacyPolicy: process.env.NUXT_PUBLIC_ROBOTS_PRIVACY_POLICY || 'all',
  robotsTermsAndConditions: process.env.NUXT_PUBLIC_ROBOTS_TERMS_AND_CONDITIONS || 'all',
  robotsSearchResult: process.env.NUXT_PUBLIC_SEARCH_RESULT || 'all',
  robotsAccessibilityDeclaration: process.env.NUXT_PUBLIC_ROBOTS_ACCESSIBILITY_DECLARATION || 'all',
  robotsStopIndexing: process.env.NUXT_PUBLIC_ROBOTS_STOP_INDEXING || '0',
  robotsItemPage: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || 'ALL',
  robotsItemPageId: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || '1',
  itemCanonicalId: process.env.NUXT_PUBLIC_ITEM_CANONICAL_ID || '',
  seoRichSnippetBrand: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || '1',
  seoRichSnippetBrandId: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || '',
  seoRichSnippetManufacturer: process.env.NUXT_PUBLIC_ROBOTS_ITEM_PAGE || '1',
  seoRichSnippetBarcodeGtin: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN || '1',
  seoRichSnippetBarcodeGtinId: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN_ID || '',
  seoRichSnippetBarcodeGtin8: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN8 || '1',
  seoRichSnippetBarcodeGtin8Id: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN8_ID || '',
  seoRichSnippetBarcodeGtin13: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN13 || '1',
  seoRichSnippetBarcodeGtin13Id: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_GTIN13_ID || '',
  seoRichSnippetBarcodeIsbn: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_ISBN || '1',
  seoRichSnippetBarcodeIsbnId: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_BARCODE_ISBN_ID || '',
  seoRichSnippetMpnBarcode: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_MPN_BARCODE || '1',
  seoRichSnippetMpnBarcodeId: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_MPN_BARCODE_ID || '',
  seoRichSnippetIdForPriceValidity: process.env.NUXT_PUBLIC_SEO_RICH_SNIPPET_PRICE_VALIDITY || '1',
  seoRichSnippetSkuBarcode: process.env.NUXT_PUBLIC_SEO_RICH_SKU_BARCODE || '1',
  seoRichSnippetSkuBarcodeId: process.env.NUXT_PUBLIC_SEO_RICH_SKU_BARCODE_ID || '',
  robotsUrlWithParameters: process.env.NUXT_PUBLIC_ROBOTS_URL_WITH_PARAMETERS || 'false',
  itemConditionNew: process.env.NUXT_PUBLIC_ITEM_CONDITION_NEW || '',
  itemConditionUsed: process.env.NUXT_PUBLIC_ITEM_CONDITION_USED || '',
  itemConditionNewBox: process.env.NUXT_PUBLIC_ITEM_CONDITION_NEW_BOX || '',
  itemConditionNewLabel: process.env.NUXT_PUBLIC_ITEM_CONDITION_NEW_LABEL || '',
  itemConditionBStock: process.env.NUXT_PUBLIC_ITEM_CONDITION_B_STOCK || '',
  seoAvailability1: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY1 || '',
  seoAvailability2: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY2 || '',
  seoAvailability3: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY3 || '',
  seoAvailability4: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY4 || '',
  seoAvailability5: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY5 || '',
  seoAvailability6: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY6 || '',
  seoAvailability7: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY7 || '',
  seoAvailability8: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY8 || '',
  seoAvailability9: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY9 || '',
  seoAvailability10: process.env.NUXT_PUBLIC_ITEM_SEO_AVAILABILITY10 || '',
  enableGoogleAnalytics: process.env.NUXT_PUBLIC_ENABLE_GOOGLE_ANALITICS || 'false',
  googleAnalyticsTrackingId: process.env.NUXT_PUBLIC_GOOGLE_ANALITICS_TRACKING_ID || '',
  sendGrossPricesToGoogleAnalytics: process.env.NUXT_PUBLIC_SEND_GROSS_PRICES_TO_GOOGLE_ANALITICS || 'false',
  googleAnalyticsCookieGroup: process.env.NUXT_PUBLIC_GOOGLE_ANALITICS_COOKIE_GROUP || 'CookieBar.marketing.label',
  registerCookieAsOptOut: process.env.NUXT_PUBLIC_REGISTER_COOKIE_AS_OPT_OUT || 'false',
  sortingDynamicInherit: process.env.NUXT_PUBLIC_SORTING_DINAMIC_INHERIT || '[]',
  sortingDynamicPrio1: process.env.NUXT_PUBLIC_SORTING_DYNAMIC_PRIO1 || 'filter.prices.price_asc',
  sortingDynamicPrio2: process.env.NUXT_PUBLIC_SORTING_DYNAMIC_PRIO2 || 'filter.prices.price_asc',
  themeColor: process.env.NUXT_PUBLIC_PRIMARY_COLOR || '#062633',
  headerLogo:
    process.env.NUXT_PUBLIC_HEADER_LOGO ||
    process.env.LOGO ||
    'https://cdn02.plentymarkets.com/mevofvd5omld/frontend/Logo/logo.svg',
  homepageCategoryId: Number(process.env.HOMEPAGE) ?? null,
  storename: process.env.NAME || 'PlentyONE GmbH',
  noCache: process.env.NO_CACHE || '',
  configId: process.env.CONFIG_ID || '',
  isHero: true,
  font: process.env.NUXT_PUBLIC_FONT || 'Red Hat Text',
  verticalBlockSize: process.env.NUXT_PUBLIC_VERTICAL_BLOCK_SIZE || 'm',
  horizontalBlockSize: process.env.NUXT_PUBLIC_HORIZONTAL_BLOCK_SIZE || 's',
  primaryColor: process.env.NUXT_PUBLIC_PRIMARY_COLOR || '#062633',
  defaultSortingOption: process.env.NUXT_PUBLIC_DEFAULT_SORTING_OPTION ?? 'texts.name1_asc',
  defaultSortingSearch: process.env.NUXT_PUBLIC_DEFAULT_SORTING_SEARCH ?? 'item.score',
  availableSortingOptions:
    process.env.NUXT_PUBLIC_AVAILABLE_SORTING_OPTIONS ||
    '["item.score","texts.name1_asc","default.recommended_sorting","sorting.price.avg_asc","sorting.price.avg_desc","variation.availability.averageDays_asc","variation.availability.averageDays_desc"]',
  recommendedFirstSortingOption: process.env.NUXT_PUBLIC_RECOMMENDED_FIRST_SORTING_OPTION ?? 'variation.position_desc',
  recommendedSecondSortingOption: process.env.NUXT_PUBLIC_RECOMMENDED_SECOND_SORTING_OPTION ?? 'sorting.price.avg_asc',
  recommendedThirdSortingOption:
    process.env.NUXT_PUBLIC_RECOMMENDED_THIRD_SORTING_OPTION ?? 'variation.availability.averageDays_asc',
  secondaryColor: process.env.NUXT_PUBLIC_SECONDARY_COLOR || '#31687d',
  headerBackgroundColor:
    process.env.NUXT_PUBLIC_HEADER_BACKGROUND_COLOR || process.env.NUXT_PUBLIC_PRIMARY_COLOR || '#062633',
  iconColor: process.env.NUXT_PUBLIC_ICON_COLOR || '#ffffff',
  showCustomerWishComponent: process.env.NUXT_PUBLIC_SHOW_CUSTOMER_WISH_COMPONENT === 'true',
  showCustomerReferenceComponent: process.env.NUXT_PUBLIC_SHOW_CUSTOMER_REFERENCE_COMPONENT === 'true',
  bundleItemDisplay: process.env.NUXT_PUBLIC_BUNDLE_ITEM_DISPLAY || '2',
  externalVatCheckInactive: process.env.NUXT_PUBLIC_EXTERNAL_VAT_CHECK_INACTIVE === 'true',
  showNotifyMe: process.env.NUXT_PUBLIC_SHOW_NOTIFY_ME === 'true',
  itemSortByMonthlySales: process.env.NUXT_PUBLIC_ITEM_SORT_BY_MONTHLY_SALES || '0',
  defaultCustomerClassId: process.env.NUXT_PUBLIC_DEFAULT_CUSTOMER_CLASS_ID || '0',
  defaultB2BCustomerClass: process.env.NUXT_PUBLIC_DEFAULT_B2B_CUSTOMER_CLASS || '0',
  fetchDynamicTranslations: false,
  sessionLifetime: process.env.NUXT_PUBLIC_SESSION_LIFETIME || '3600',
  shippingTextCategoryId: process.env.NUXT_PUBLIC_SHIPPING_TEXT_CATEGORY_ID || '',
  manufacturerName: process.env.NUXT_PUBLIC_MANUFACTURER_NAME || '0',
  manufacturerExternalName: process.env.NUXT_PUBLIC_MANUFACTURER_EXTERNAL_NAME || '0',
  manufacturerLegalName: process.env.NUXT_PUBLIC_MANUFACTURER_LEGAL_NAME || '0',
  manufacturerLogo: process.env.NUXT_PUBLIC_MANUFACTURER_LOGO || '0',
  manufacturerUrl: process.env.NUXT_PUBLIC_MANUFACTURER_URL || '0',
  manufacturerStreet: process.env.NUXT_PUBLIC_MANUFACTURER_STREET || '0',
  manufacturerHouseNo: process.env.NUXT_PUBLIC_MANUFACTURER_HOUSE_NO || '0',
  manufacturerPostcode: process.env.NUXT_PUBLIC_MANUFACTURER_POSTCODE || '0',
  manufacturerTown: process.env.NUXT_PUBLIC_MANUFACTURER_TOWN || '0',
  manufacturerCountryId: process.env.NUXT_PUBLIC_MANUFACTURER_COUNTRY_ID || '0',
  manufacturerPhoneNumber: process.env.NUXT_PUBLIC_MANUFACTURER_PHONE_NUMBER || '0',
  manufacturerFaxNumber: process.env.NUXT_PUBLIC_MANUFACTURER_FAX_NUMBER || '0',
  manufacturerEmail: process.env.NUXT_PUBLIC_MANUFACTURER_EMAIL || '0',
  manufacturerContactUrl: process.env.NUXT_PUBLIC_MANUFACTURER_CONTACT_URL || '0',
  customAssetsSafeMode: process.env.NUXT_PUBLIC_CUSTOM_ASSETS_SAFE_MODE === 'true',
};
