import type { Category } from '@plentymarkets/shop-api';

export const CategoryMock: Category = {
  id: 17,
  parentCategoryId: 16,
  level: 2,
  type: 'item',
  linklist: 'Y',
  right: 'all',
  sitemap: 'Y',
  details: [
    {
      categoryId: '17',
      lang: 'de',
      name: 'Sessel & Hocker',
      description: '',
      description2: '',
      shortDescription: '',
      metaKeywords: 'moebel, sessel, hocker, wohnzimmer',
      metaDescription: '',
      nameUrl: 'sessel-hocker',
      metaTitle: '',
      position: '5',
      itemListView: 'ItemViewCategoriesList',
      singleItemView: 'ItemViewSingleItem',
      pageView: 'PageDesignContent',
      fulltext: 'N',
      metaRobots: 'ALL',
      canonicalLink: '',
      updatedAt: '2021-11-16T08:28:25+01:00',
      updatedBy: 'Plentymarkets Support',
      plenty_category_details_image_path: '',
      plenty_category_details_image2_path: '',
      image: null,
      imagePath: null,
      image2: null,
      image2Path: null,
      plentyId: 60796,
    },
  ],
  clients: [
    {
      categoryId: '17',
      plentyId: 60796,
    },
  ],
};
