import type { CategoryTreeItem } from '@plentymarkets/shop-api';

export const CategoryTreeMock: CategoryTreeItem[] = [
  {
    id: 73,
    type: 'item',
    childCount: 0,
    right: 'all',
    itemCount: [
      {
        categoryId: '73',
        webstoreId: '0',
        lang: 'de',
        count: '8',
        createdAt: '2022-06-27 09:23:46',
        updatedAt: '2024-01-09 13:35:22',
        variationCount: '8',
        customerClassId: '0',
      },
    ],
    details: [
      {
        lang: 'de',
        name: 'Gear',
        nameUrl: 'gear',
        metaTitle: '',
        imagePath: null,
        image2Path: null,
      },
    ],
  },
  {
    id: 48,
    type: 'item',
    childCount: 0,
    right: 'all',
    itemCount: [
      {
        categoryId: '48',
        webstoreId: '0',
        lang: 'de',
        count: '1',
        createdAt: '2022-06-27 09:23:46',
        updatedAt: '2024-01-09 13:35:22',
        variationCount: '1',
        customerClassId: '0',
      },
    ],
    details: [
      {
        lang: 'de',
        name: 'Gutscheine',
        nameUrl: 'gutscheine',
        metaTitle: '',
        imagePath: null,
        image2Path: null,
      },
    ],
  },
  {
    id: 49,
    type: 'item',
    childCount: 2,
    right: 'all',
    itemCount: [
      {
        categoryId: '49',
        webstoreId: '0',
        lang: 'de',
        count: '76',
        createdAt: '2022-06-27 09:23:46',
        updatedAt: '2024-01-09 13:35:22',
        variationCount: '136',
        customerClassId: '0',
      },
    ],
    details: [
      {
        lang: 'de',
        name: 'Wear',
        nameUrl: 'wear',
        metaTitle: '',
        imagePath: null,
        image2Path: null,
      },
    ],
    children: [
      {
        id: 51,
        type: 'item',
        childCount: 10,
        right: 'all',
        itemCount: [
          {
            categoryId: '51',
            webstoreId: '0',
            lang: 'de',
            count: '28',
            createdAt: '2022-06-27 09:23:46',
            updatedAt: '2024-01-09 13:35:22',
            variationCount: '28',
            customerClassId: '0',
          },
        ],
        details: [
          {
            lang: 'de',
            name: 'Men',
            nameUrl: 'men',
            metaTitle: '',
            imagePath: null,
            image2Path: null,
          },
        ],
        children: [
          {
            id: 61,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '61',
                webstoreId: '0',
                lang: 'de',
                count: '2',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '2',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Accessories',
                nameUrl: 'accessories',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 64,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '64',
                webstoreId: '0',
                lang: 'de',
                count: '4',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '4',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Indoor',
                nameUrl: 'indoor',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 54,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '54',
                webstoreId: '0',
                lang: 'de',
                count: '1',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '1',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Jackets',
                nameUrl: 'jackets',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 59,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '59',
                webstoreId: '0',
                lang: 'de',
                count: '4',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '4',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Outdoor',
                nameUrl: 'outdoor',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 58,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '58',
                webstoreId: '0',
                lang: 'de',
                count: '1',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '1',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Pants',
                nameUrl: 'pants',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 56,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '56',
                webstoreId: '0',
                lang: 'de',
                count: '2',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '2',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Shoes',
                nameUrl: 'shoes',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 57,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '57',
                webstoreId: '0',
                lang: 'de',
                count: '3',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '3',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Sport',
                nameUrl: 'sport',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 55,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '55',
                webstoreId: '0',
                lang: 'de',
                count: '1',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '1',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Sweats',
                nameUrl: 'sweats',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 53,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '53',
                webstoreId: '0',
                lang: 'de',
                count: '1',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '1',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'T-Shirts',
                nameUrl: 't-shirts',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 52,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '52',
                webstoreId: '0',
                lang: 'de',
                count: '4',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '4',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Winter',
                nameUrl: 'winter',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
        ],
      },
      {
        id: 50,
        type: 'item',
        childCount: 10,
        right: 'all',
        itemCount: [
          {
            categoryId: '50',
            webstoreId: '0',
            lang: 'de',
            count: '40',
            createdAt: '2022-06-27 09:23:46',
            updatedAt: '2024-01-09 13:35:22',
            variationCount: '88',
            customerClassId: '0',
          },
        ],
        details: [
          {
            lang: 'de',
            name: 'Women',
            nameUrl: 'women',
            metaTitle: '',
            imagePath: null,
            image2Path: null,
          },
        ],
        children: [
          {
            id: 66,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '66',
                webstoreId: '0',
                lang: 'de',
                count: '5',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '17',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Accessories',
                nameUrl: 'accessories',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 72,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '72',
                webstoreId: '0',
                lang: 'de',
                count: '4',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '4',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Indoor',
                nameUrl: 'indoor',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 70,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '70',
                webstoreId: '0',
                lang: 'de',
                count: '1',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '1',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Jackets',
                nameUrl: 'jackets',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 60,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '60',
                webstoreId: '0',
                lang: 'de',
                count: '7',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '19',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Outdoor',
                nameUrl: 'outdoor',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 67,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '67',
                webstoreId: '0',
                lang: 'de',
                count: '1',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '1',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Pants',
                nameUrl: 'pants',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 68,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '68',
                webstoreId: '0',
                lang: 'de',
                count: '2',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '2',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Shoes',
                nameUrl: 'shoes',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 63,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '63',
                webstoreId: '0',
                lang: 'de',
                count: '5',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '5',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Sport',
                nameUrl: 'sport',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 69,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '69',
                webstoreId: '0',
                lang: 'de',
                count: '1',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '1',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Sweats',
                nameUrl: 'sweats',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 71,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '71',
                webstoreId: '0',
                lang: 'de',
                count: '1',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '1',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'T-Shirts',
                nameUrl: 't-shirts',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
          {
            id: 65,
            type: 'item',
            childCount: 0,
            right: 'all',
            itemCount: [
              {
                categoryId: '65',
                webstoreId: '0',
                lang: 'de',
                count: '5',
                createdAt: '2022-06-27 09:23:46',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '17',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Winter',
                nameUrl: 'winter',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    id: 16,
    type: 'item',
    childCount: 3,
    right: 'all',
    itemCount: [
      {
        categoryId: '16',
        webstoreId: '0',
        lang: 'de',
        count: '36',
        createdAt: '2022-06-27 09:23:46',
        updatedAt: '2024-01-09 13:35:22',
        variationCount: '59',
        customerClassId: '0',
      },
    ],
    details: [
      {
        lang: 'de',
        name: 'Wohnzimmer',
        nameUrl: 'wohnzimmer',
        metaTitle: 'Möbel für Wohnzimmer',
        imagePath: 'category/16/slider-living-1920x.jpg',
        image2Path: null,
      },
    ],
    children: [
      {
        id: 18,
        type: 'item',
        childCount: 1,
        right: 'all',
        itemCount: [
          {
            categoryId: '18',
            webstoreId: '0',
            lang: 'de',
            count: '15',
            createdAt: '2022-06-27 09:23:46',
            updatedAt: '2024-01-09 13:35:22',
            variationCount: '18',
            customerClassId: '0',
          },
        ],
        details: [
          {
            lang: 'de',
            name: 'Sofas',
            nameUrl: 'sofas',
            metaTitle: '',
            imagePath: null,
            image2Path: null,
          },
        ],
        children: [
          {
            id: 74,
            type: 'item',
            childCount: 1,
            right: 'all',
            itemCount: [
              {
                categoryId: '74',
                webstoreId: '0',
                lang: 'de',
                count: '5',
                createdAt: '2022-07-13 13:49:52',
                updatedAt: '2024-01-09 13:35:22',
                variationCount: '6',
                customerClassId: '0',
              },
            ],
            details: [
              {
                lang: 'de',
                name: 'Leder Sofas',
                nameUrl: 'leder-sofas',
                metaTitle: '',
                imagePath: null,
                image2Path: null,
              },
            ],
            children: [
              {
                id: 75,
                type: 'item',
                childCount: 1,
                right: 'all',
                itemCount: [
                  {
                    categoryId: '75',
                    webstoreId: '0',
                    lang: 'de',
                    count: '3',
                    createdAt: '2022-07-13 14:24:39',
                    updatedAt: '2024-01-09 13:35:22',
                    variationCount: '3',
                    customerClassId: '0',
                  },
                ],
                details: [
                  {
                    lang: 'de',
                    name: 'chesterfield sofas',
                    nameUrl: 'chesterfield-sofas',
                    metaTitle: '',
                    imagePath: null,
                    image2Path: null,
                  },
                ],
                children: [
                  {
                    id: 76,
                    type: 'item',
                    childCount: 1,
                    right: 'all',
                    itemCount: [
                      {
                        categoryId: '76',
                        webstoreId: '0',
                        lang: 'de',
                        count: '2',
                        createdAt: '2022-07-20 15:48:40',
                        updatedAt: '2024-01-09 13:35:22',
                        variationCount: '2',
                        customerClassId: '0',
                      },
                    ],
                    details: [
                      {
                        lang: 'de',
                        name: 'test',
                        nameUrl: 'test',
                        metaTitle: '',
                        imagePath: null,
                        image2Path: null,
                      },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: 17,
        type: 'item',
        childCount: 0,
        right: 'all',
        itemCount: [
          {
            categoryId: '17',
            webstoreId: '0',
            lang: 'de',
            count: '18',
            createdAt: '2022-06-27 09:23:46',
            updatedAt: '2024-01-09 13:35:22',
            variationCount: '18',
            customerClassId: '0',
          },
        ],
        details: [
          {
            lang: 'de',
            name: 'Sessel & Hocker',
            nameUrl: 'sessel-hocker',
            metaTitle: '',
            imagePath: null,
            image2Path: null,
          },
        ],
      },
      {
        id: 46,
        type: 'item',
        childCount: 0,
        right: 'all',
        itemCount: [
          {
            categoryId: '46',
            webstoreId: '0',
            lang: 'de',
            count: '1',
            createdAt: '2022-06-27 09:23:46',
            updatedAt: '2024-01-09 13:35:22',
            variationCount: '1',
            customerClassId: '0',
          },
        ],
        details: [
          {
            lang: 'de',
            name: 'Artikelpaket',
            nameUrl: 'artikelpaket',
            metaTitle: '',
            imagePath: null,
            image2Path: null,
          },
        ],
      },
    ],
  },
  {
    id: 19,
    type: 'item',
    childCount: 1,
    right: 'all',
    itemCount: [
      {
        categoryId: '19',
        webstoreId: '0',
        lang: 'de',
        count: '6',
        createdAt: '2022-06-27 09:23:46',
        updatedAt: '2024-01-09 13:35:22',
        variationCount: '6',
        customerClassId: '0',
      },
    ],
    details: [
      {
        lang: 'de',
        name: 'Arbeitszimmer & Büro',
        nameUrl: 'arbeitszimmer-buero',
        metaTitle: 'Möbel für Arbeitszimmer & Büro',
        imagePath: null,
        image2Path: null,
      },
    ],
    children: [
      {
        id: 20,
        type: 'item',
        childCount: 0,
        right: 'all',
        itemCount: [
          {
            categoryId: '20',
            webstoreId: '0',
            lang: 'de',
            count: '6',
            createdAt: '2022-06-27 09:23:46',
            updatedAt: '2024-01-09 13:35:22',
            variationCount: '6',
            customerClassId: '0',
          },
        ],
        details: [
          {
            lang: 'de',
            name: 'Bürostühle',
            nameUrl: 'buerostuehle',
            metaTitle: 'Optimale Bürostühle für ihr Arbeitszimmer oder Büro',
            imagePath: null,
            image2Path: null,
          },
        ],
      },
    ],
  },
  {
    id: 44,
    type: 'item',
    childCount: 0,
    right: 'all',
    itemCount: [
      {
        categoryId: '44',
        webstoreId: '0',
        lang: 'de',
        count: '2',
        createdAt: '2022-06-27 09:23:46',
        updatedAt: '2024-01-09 13:35:22',
        variationCount: '2',
        customerClassId: '0',
      },
    ],
    details: [
      {
        lang: 'de',
        name: 'Sets',
        nameUrl: 'sets',
        metaTitle: '',
        imagePath: null,
        image2Path: null,
      },
    ],
  },
];
