export const FacetMock = {
  data: {
    category: {
      id: 17,
      parentCategoryId: 16,
      level: 2,
      type: 'item',
      linklist: 'Y',
      right: 'all',
      sitemap: 'Y',
      details: [
        {
          categoryId: '17',
          lang: 'de',
          name: 'Sessel & Hocker',
          description: '',
          description2: '',
          shortDescription: '',
          metaKeywords: 'moebel, sessel, hocker, wohnzimmer',
          metaDescription: '',
          nameUrl: 'sessel-hocker',
          metaTitle: '',
          position: '5',
          itemListView: 'ItemViewCategoriesList',
          singleItemView: 'ItemViewSingleItem',
          pageView: 'PageDesignContent',
          fulltext: 'N',
          metaRobots: 'ALL',
          canonicalLink: '',
          updatedAt: '2021-11-16T08:28:25+01:00',
          updatedBy: 'Plentymarkets Support',
          plenty_category_details_image_path: '',
          plenty_category_details_image2_path: '',
          image: null,
          imagePath: null,
          image2: null,
          image2Path: null,
          plentyId: 60796,
        },
      ],
      clients: [
        {
          categoryId: '17',
          plentyId: 60796,
        },
      ],
    },
    products: [
      {
        images: {
          all: [
            {
              names: {
                name: '',
                lang: 'de',
                imageId: 23,
                alternate: '',
              },
              urlMiddle:
                'https://cdn02.plentymarkets.com/mevofvd5omld/item/images/109/middle/109-Barhocker-White-SanFrancisco.jpg',
              position: 0,
              path: 'S3:109:109-Barhocker-White-SanFrancisco.jpg',
              cleanImageName: '109-Barhocker-White-SanFrancisco.jpg',
            },
          ],
          variation: [],
        },
        item: {
          id: 109,
          storeSpecial: null,
          manufacturerId: 2,
          itemType: 'default',
          manufacturer: {
            position: 0,
            externalName: 'A & C Design',
          },
          rebate: 0,
          salableVariationCount: 1,
          customsTariffNumber: '',
          producingCountry: {
            names: [],
          },
          condition: {
            names: [],
          },
        },
        texts: {
          urlPath: 'wohnzimmer/sessel-hocker/barhocker-white-sanfrancisco',
          name3: '',
          name2: '',
          lang: 'de',
          name1: 'Barhocker White SanFrancisco (Staffelpreise)',
        },
        defaultCategories: [
          {
            id: 17,
            parentCategoryId: 16,
            level: 2,
            type: 'item',
            linklist: true,
            right: 'all',
            sitemap: true,
            updatedAt: '2021-11-16T08:28:25+01:00',
            manually: false,
            plentyId: 60796,
          },
        ],
        variation: {
          itemId: 109,
          availabilityId: 1,
          maximumOrderQuantity: null,
          minimumOrderQuantity: 1,
          intervalOrderQuantity: 1,
          releasedAt: null,
          name: '',
          vatId: 0,
          bundleType: null,
          mayShowUnitPrice: true,
          availability: {
            id: 1,
            icon: 'av1.gif',
            averageDays: 2,
            createdAt: '2022-06-27 09:20:16',
            updatedAt: '2022-06-27 09:20:16',
            names: {
              id: 41,
              availabilityId: 1,
              lang: 'de',
              name: 'Sofort versandfertig, Lieferzeit 48h',
              createdAt: '2022-06-27 09:20:16',
              updatedAt: '2022-06-27 09:20:16',
            },
          },
          id: 1007,
          availabilityUpdatedAt: '2018-02-28T11:49:53+01:00',
          model: '',
        },
        filter: {
          isSalable: true,
          isSalableAndActive: true,
          hasActiveChildren: false,
          hasChildren: true,
        },
        unit: {
          names: {
            unitId: 1,
            lang: 'de',
            name: 'Stück',
          },
          unitOfMeasurement: 'C62',
          content: 1,
        },
        properties: [],
        hasOrderProperties: false,
        hasRequiredOrderProperty: false,
        groupedAttributes: [],
        prices: {
          default: {
            price: {
              value: 110,
              formatted: '110,00 EUR',
            },
            unitPrice: {
              value: 110,
              formatted: '110,00 EUR',
            },
            basePrice: '110,00 EUR / Stück',
            baseLot: 1,
            baseUnit: 'C62',
            baseSinglePrice: 110,
            minimumOrderQuantity: 1,
            contactClassDiscount: {
              percent: 0,
              amount: 0,
            },
            categoryDiscount: {
              percent: 0,
              amount: 0,
            },
            currency: 'EUR',
            lowestPrice: {
              value: null,
              formatted: '',
            },
            vat: {
              id: 0,
              value: 19,
            },
            isNet: false,
            data: {
              salesPriceId: 1,
              price: 110,
              priceNet: 92.436974789916,
              basePrice: 110,
              basePriceNet: 92.436974789916,
              unitPrice: 110,
              unitPriceNet: 92.436974789916,
              lowestPrice: null,
              lowestPriceNet: null,
              customerClassDiscountPercent: 0,
              customerClassDiscount: 0,
              customerClassDiscountNet: 0,
              categoryDiscountPercent: 0,
              categoryDiscount: 0,
              categoryDiscountNet: 0,
              vatId: 0,
              vatValue: 19,
              currency: 'EUR',
              interval: 'none',
              conversionFactor: 1,
              minimumOrderQuantity: '1.00',
              updatedAt: '2022-03-18 10:29:04',
              type: 'default',
              pricePosition: '0',
            },
          },
          rrp: {
            price: {
              value: 150,
              formatted: '150,00 EUR',
            },
            unitPrice: {
              value: 150,
              formatted: '150,00 EUR',
            },
            basePrice: '150,00 EUR / Stück',
            baseLot: 1,
            baseUnit: 'C62',
            baseSinglePrice: 150,
            minimumOrderQuantity: 0,
            contactClassDiscount: {
              percent: 0,
              amount: 0,
            },
            categoryDiscount: {
              percent: 0,
              amount: 0,
            },
            currency: 'EUR',
            lowestPrice: {
              value: null,
              formatted: '',
            },
            vat: {
              id: 0,
              value: 19,
            },
            isNet: false,
            data: {
              salesPriceId: 2,
              price: 150,
              priceNet: 126.05042016807,
              basePrice: 150,
              basePriceNet: 126.05042016807,
              unitPrice: 150,
              unitPriceNet: 126.05042016807,
              lowestPrice: null,
              lowestPriceNet: null,
              customerClassDiscountPercent: 0,
              customerClassDiscount: 0,
              customerClassDiscountNet: 0,
              categoryDiscountPercent: 0,
              categoryDiscount: 0,
              categoryDiscountNet: 0,
              vatId: 0,
              vatValue: 19,
              currency: 'EUR',
              interval: 'none',
              conversionFactor: 1,
              minimumOrderQuantity: '0.00',
              updatedAt: '2022-03-18 10:29:04',
              type: 'rrp',
              pricePosition: '0',
            },
          },
          set: null,
          specialOffer: null,
          graduatedPrices: [
            {
              price: {
                value: 90,
                formatted: '90,00 EUR',
              },
              unitPrice: {
                value: 90,
                formatted: '90,00 EUR',
              },
              basePrice: '90,00 EUR / Stück',
              baseLot: 1,
              baseUnit: 'C62',
              baseSinglePrice: 90,
              minimumOrderQuantity: 5,
              contactClassDiscount: {
                percent: 0,
                amount: 0,
              },
              categoryDiscount: {
                percent: 0,
                amount: 0,
              },
              currency: 'EUR',
              lowestPrice: {
                value: null,
                formatted: '',
              },
              vat: {
                id: 0,
                value: 19,
              },
              isNet: false,
              data: {
                salesPriceId: 6,
                price: 90,
                priceNet: 75.63025210084,
                basePrice: 90,
                basePriceNet: 75.63025210084,
                unitPrice: 90,
                unitPriceNet: 75.63025210084,
                lowestPrice: null,
                lowestPriceNet: null,
                customerClassDiscountPercent: 0,
                customerClassDiscount: 0,
                customerClassDiscountNet: 0,
                categoryDiscountPercent: 0,
                categoryDiscount: 0,
                categoryDiscountNet: 0,
                vatId: 0,
                vatValue: 19,
                currency: 'EUR',
                interval: 'none',
                conversionFactor: 1,
                minimumOrderQuantity: '5.00',
                updatedAt: '2022-03-18 10:29:04',
                type: 'default',
                pricePosition: '6',
              },
            },
            {
              price: {
                value: 100,
                formatted: '100,00 EUR',
              },
              unitPrice: {
                value: 100,
                formatted: '100,00 EUR',
              },
              basePrice: '100,00 EUR / Stück',
              baseLot: 1,
              baseUnit: 'C62',
              baseSinglePrice: 100,
              minimumOrderQuantity: 3,
              contactClassDiscount: {
                percent: 0,
                amount: 0,
              },
              categoryDiscount: {
                percent: 0,
                amount: 0,
              },
              currency: 'EUR',
              lowestPrice: {
                value: null,
                formatted: '',
              },
              vat: {
                id: 0,
                value: 19,
              },
              isNet: false,
              data: {
                salesPriceId: 5,
                price: 100,
                priceNet: 84.033613445378,
                basePrice: 100,
                basePriceNet: 84.033613445378,
                unitPrice: 100,
                unitPriceNet: 84.033613445378,
                lowestPrice: null,
                lowestPriceNet: null,
                customerClassDiscountPercent: 0,
                customerClassDiscount: 0,
                customerClassDiscountNet: 0,
                categoryDiscountPercent: 0,
                categoryDiscount: 0,
                categoryDiscountNet: 0,
                vatId: 0,
                vatValue: 19,
                currency: 'EUR',
                interval: 'none',
                conversionFactor: 1,
                minimumOrderQuantity: '3.00',
                updatedAt: '2022-03-18 10:29:04',
                type: 'default',
                pricePosition: '5',
              },
            },
            {
              price: {
                value: 110,
                formatted: '110,00 EUR',
              },
              unitPrice: {
                value: 110,
                formatted: '110,00 EUR',
              },
              basePrice: '110,00 EUR / Stück',
              baseLot: 1,
              baseUnit: 'C62',
              baseSinglePrice: 110,
              minimumOrderQuantity: 1,
              contactClassDiscount: {
                percent: 0,
                amount: 0,
              },
              categoryDiscount: {
                percent: 0,
                amount: 0,
              },
              currency: 'EUR',
              lowestPrice: {
                value: null,
                formatted: '',
              },
              vat: {
                id: 0,
                value: 19,
              },
              isNet: false,
              data: {
                salesPriceId: 1,
                price: 110,
                priceNet: 92.436974789916,
                basePrice: 110,
                basePriceNet: 92.436974789916,
                unitPrice: 110,
                unitPriceNet: 92.436974789916,
                lowestPrice: null,
                lowestPriceNet: null,
                customerClassDiscountPercent: 0,
                customerClassDiscount: 0,
                customerClassDiscountNet: 0,
                categoryDiscountPercent: 0,
                categoryDiscount: 0,
                categoryDiscountNet: 0,
                vatId: 0,
                vatValue: 19,
                currency: 'EUR',
                interval: 'none',
                conversionFactor: 1,
                minimumOrderQuantity: '1.00',
                updatedAt: '2022-03-18 10:29:04',
                type: 'default',
                pricePosition: '0',
              },
            },
          ],
        },
        facets: [],
        attributes: [],
      },
    ],
    facets: [
      {
        id: 'feedback',
        name: 'Artikelbewertung',
        position: 10,
        names: [
          {
            lang: 'de',
            name: 'Artikelbewertung',
          },
          {
            lang: 'en',
            name: 'Item rating',
          },
        ],
        values: [
          {
            id: 'feedback-2',
            names: [
              {
                lang: 'de',
                name: '',
              },
            ],
            count: 1,
            selected: 21,
          },
        ],
        minHitCount: 1,
        maxResultCount: 5,
        type: 'feedback',
        count: 1,
      },
      {
        id: 6,
        name: 'Eigenschaft',
        cssClass: '',
        position: 1,
        sort: 'position',
        minHitCount: '1',
        maxResultCount: '50',
        count: 1,
        values: [
          {
            id: 19,
            name: 'Wert 1',
            cssClass: '',
            position: 1,
            count: 1,
            selected: false,
          },
          {
            id: 20,
            name: 'Wert 2',
            cssClass: '',
            position: 1,
            count: 1,
            selected: false,
          },
        ],
        type: 'dynamic',
      },
      {
        id: 1,
        name: 'Hersteller',
        cssClass: '',
        position: 1,
        sort: 'position',
        minHitCount: '1',
        maxResultCount: '50',
        count: 18,
        values: [
          {
            id: 1,
            name: 'Exclusive Leather',
            cssClass: '',
            position: 1,
            count: 5,
            selected: false,
          },
          {
            id: 2,
            name: 'A & C Design',
            cssClass: '',
            position: 2,
            count: 13,
            selected: false,
          },
        ],
        type: 'producer',
      },
      {
        id: 2,
        name: 'Farbe',
        cssClass: '',
        position: 2,
        sort: 'position',
        minHitCount: '1',
        maxResultCount: '50',
        count: 17,
        values: [
          {
            id: 3,
            name: 'Weiß',
            cssClass: '',
            position: 1,
            count: 2,
            selected: false,
          },
          {
            id: 4,
            name: 'Schwarz',
            cssClass: '',
            position: 2,
            count: 5,
            selected: false,
          },
          {
            id: 6,
            name: 'Rot',
            cssClass: '',
            position: 4,
            count: 4,
            selected: false,
          },
          {
            id: 8,
            name: 'Grün',
            cssClass: '',
            position: 5,
            count: 1,
            selected: false,
          },
          {
            id: 10,
            name: 'Orange',
            cssClass: '',
            position: 7,
            count: 2,
            selected: false,
          },
          {
            id: 11,
            name: 'Grau',
            cssClass: '',
            position: 8,
            count: 1,
            selected: false,
          },
          {
            id: 12,
            name: 'Natur',
            cssClass: '',
            position: 10,
            count: 2,
            selected: false,
          },
        ],
        type: 'dynamic',
      },
      {
        id: 3,
        name: 'Preis',
        cssClass: '',
        position: 3,
        sort: 'position',
        minHitCount: '1',
        maxResultCount: '50',
        count: 0,
        values: [],
        type: 'price',
      },
      {
        id: 5,
        name: 'Verfügbarkeit',
        cssClass: '',
        position: 4,
        sort: 'position',
        minHitCount: '1',
        maxResultCount: '50',
        count: 18,
        values: [
          {
            id: 14,
            name: 'Sofort versandfertig, Lieferzeit 48h',
            cssClass: '',
            position: 1,
            count: 18,
            selected: false,
          },
        ],
        type: 'availability',
      },
    ],
    languageUrls: {
      'x-default': '/living-room/armchair-stool/',
      de: '/wohnzimmer/sessel-hocker/',
      en: '/living-room/armchair-stool/',
    },
    pagination: {
      perPageOptions: [20, 40, 100],
      totals: 1,
    },
  },
};
