import type { Product } from '@plentymarkets/shop-api';

export const ProductPriceFixture: Product = {
  defaultCategories: [
    {
      id: 31,
      parentCategoryId: null,
      level: 1,
      type: 'item',
      linklist: true,
      right: 'all',
      sitemap: true,
      updatedAt: '2020-12-18T14:47:12+01:00',
      manually: false,
      plentyId: 51188,
    },
  ],
  filter: {
    hasManufacturer: false,
    isSalable: true,
    isSalableAndActive: true,
    hasActiveChildren: false,
  },
  images: {
    all: [
      {
        names: [],
        urlSecondPreview: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/secondPreview/dollar.jpg',
        urlPreview: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/preview/dollar.jpg',
        path: 'S3:203:dollar.jpg',
        height: 360,
        position: 1,
        width: 343,
        url: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/full/dollar.jpg',
        urlMiddle: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/middle/dollar.jpg',
        cleanImageName: 'dollar.jpg',
      },
      {
        urlMiddle: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/middle/dollar_1.jpg',
        position: 2,
        width: 343,
        height: 360,
        path: 'S3:203:dollar_1.jpg',
        urlPreview: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/preview/dollar_1.jpg',
        names: [],
        urlSecondPreview: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/secondPreview/dollar_1.jpg',
        url: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/full/dollar_1.jpg',
        cleanImageName: 'dollar_1.jpg',
      },
    ],
    variation: [
      {
        urlMiddle: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/middle/dollar_1.jpg',
        position: 2,
        width: 343,
        height: 360,
        path: 'S3:203:dollar_1.jpg',
        urlPreview: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/preview/dollar_1.jpg',
        names: [],
        urlSecondPreview: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/secondPreview/dollar_1.jpg',
        url: 'https://cdn02.plentymarkets.com/2x3z2pucy2z9/item/images/203/full/dollar_1.jpg',
        cleanImageName: 'dollar_1.jpg',
      },
    ],
  },
  item: {
    id: 203,
    add_cms_page: '0',
    condition: {
      id: 0,
      names: {
        lang: 'en',
        name: 'New',
      },
    },
    storeSpecial: null,
    manufacturerId: 0,
    producingCountryId: 1,
    revenueAccount: 0,
    conditionApi: {
      id: 0,
      names: {
        lang: 'en',
        name: 'New',
      },
    },
    ageRestriction: 0,
    itemType: 'default',
    producingCountry: {
      storehouseId: 0,
      names: {
        name: 'Germany',
        lang: 'en',
      },
      lang: 'de',
      active: 1,
      shippingDestinationId: 101,
      name: 'Germany',
      isoCode2: 'DE',
      isoCode3: 'DEU',
      id: 1,
      isCountryStateMandatory: null,
    },
    manufacturer: [],
    rebate: 0,
    salableVariationCount: 1,
    customsTariffNumber: '',
  },
  variation: {
    position: 0,
    number: '9999',
    model: '',
    externalId: '0',
    availabilityId: 1,
    maximumOrderQuantity: null,
    minimumOrderQuantity: 1,
    intervalOrderQuantity: 1,
    availableUntil: null,
    releasedAt: null,
    name: '',
    weightG: 0,
    weightNetG: 0,
    widthMM: 0,
    lengthMM: 0,
    heightMM: 0,
    unitsContained: 1,
    vatId: 0,
    bundleType: null,
    mayShowUnitPrice: null,
    customsTariffNumber: '0',
    availability: {
      id: 1,
      icon: 'av1.gif',
      averageDays: 2,
      createdAt: '2020-10-16 15:07:10',
      updatedAt: '2020-10-16 15:07:10',
      names: {
        id: 22,
        availabilityId: 1,
        lang: 'en',
        name: 'Ready for shipping, delivery in 48h',
        createdAt: '2020-10-16 15:07:10',
        updatedAt: '2020-10-16 15:07:10',
      },
      iconPath: '/tpl/availability/av1.gif',
    },
    id: 1145,
    unitCombinationId: 1,
    availabilityUpdatedAt: '2024-09-18T13:44:33+02:00',
  },
  texts: {
    id: 183,
    lang: 'en',
    name2: '',
    name3: '',
    description: '<p>testing some prices</p>',
    itemId: 203,
    metaDescription: '',
    technicalData: '',
    urlPath: 'testarticle/price-test',
    name1: 'price test',
    shortDescription: '',
    keywords: '',
  },
  unit: {
    names: {
      unitId: 1,
      lang: 'en',
      name: 'piece',
    },
    unitOfMeasurement: 'C62',
    content: 1,
  },
  properties: [],
  hasOrderProperties: false,
  hasRequiredOrderProperty: false,
  prices: {
    default: {
      price: {
        value: 100,
        formatted: 'EUR 100.00',
      },
      unitPrice: {
        value: 100,
        formatted: 'EUR 100.00',
      },
      basePrice: '',
      baseLot: null,
      baseUnit: null,
      baseSinglePrice: null,
      minimumOrderQuantity: 1,
      contactClassDiscount: {
        percent: 0,
        amount: 0,
      },
      categoryDiscount: {
        percent: 0,
        amount: 0,
      },
      currency: 'EUR',
      lowestPrice: {
        value: 80,
        formatted: 'EUR 80.00',
      },
      vat: {
        id: 0,
        value: 19,
      },
      isNet: false,
      data: {
        salesPriceId: 1,
        price: 100,
        priceNet: 84.033613445378,
        basePrice: 100,
        basePriceNet: 84.033613445378,
        unitPrice: 100,
        unitPriceNet: 84.033613445378,
        lowestPrice: 80,
        lowestPriceNet: 67.226890756303,
        customerClassDiscountPercent: 0,
        customerClassDiscount: 0,
        customerClassDiscountNet: 0,
        categoryDiscountPercent: 0,
        categoryDiscount: 0,
        categoryDiscountNet: 0,
        vatId: 0,
        vatValue: 19,
        currency: 'EUR',
        interval: 'none',
        conversionFactor: 1,
        minimumOrderQuantity: '1.00',
        updatedAt: '2024-09-18 13:49:14',
        type: 'default',
        pricePosition: 0,
      },
    },
    rrp: {
      price: {
        value: 120,
        formatted: 'EUR 120.00',
      },
      unitPrice: {
        value: 120,
        formatted: 'EUR 120.00',
      },
      basePrice: '',
      baseLot: null,
      baseUnit: null,
      baseSinglePrice: null,
      minimumOrderQuantity: 0,
      contactClassDiscount: {
        percent: 0,
        amount: 0,
      },
      categoryDiscount: {
        percent: 0,
        amount: 0,
      },
      currency: 'EUR',
      lowestPrice: {
        value: null,
        formatted: '',
      },
      vat: {
        id: 0,
        value: 19,
      },
      isNet: false,
      data: {
        salesPriceId: 2,
        price: 120,
        priceNet: 100.84033613445,
        basePrice: 120,
        basePriceNet: 100.84033613445,
        unitPrice: 120,
        unitPriceNet: 100.84033613445,
        lowestPrice: 0,
        lowestPriceNet: 0,
        customerClassDiscountPercent: 0,
        customerClassDiscount: 0,
        customerClassDiscountNet: 0,
        categoryDiscountPercent: 0,
        categoryDiscount: 0,
        categoryDiscountNet: 0,
        vatId: 0,
        vatValue: 19,
        currency: 'EUR',
        interval: 'none',
        conversionFactor: 1,
        minimumOrderQuantity: '0.00',
        updatedAt: '2024-09-18 13:49:14',
        type: 'rrp',
        pricePosition: 0,
      },
    },
    set: null,
    specialOffer: {
      price: {
        value: 80,
        formatted: 'EUR 80.00',
      },
      unitPrice: {
        value: 80,
        formatted: 'EUR 80.00',
      },
      basePrice: '',
      baseLot: null,
      baseUnit: null,
      baseSinglePrice: null,
      minimumOrderQuantity: 1,
      contactClassDiscount: {
        percent: 0,
        amount: 0,
      },
      categoryDiscount: {
        percent: 0,
        amount: 0,
      },
      currency: 'EUR',
      lowestPrice: {
        value: null,
        formatted: '',
      },
      vat: {
        id: 0,
        value: 19,
      },
      isNet: false,
      data: {
        salesPriceId: 7,
        price: 80,
        priceNet: 67.226890756303,
        basePrice: 80,
        basePriceNet: 67.226890756303,
        unitPrice: 80,
        unitPriceNet: 67.226890756303,
        lowestPrice: 0,
        lowestPriceNet: 0,
        customerClassDiscountPercent: 0,
        customerClassDiscount: 0,
        customerClassDiscountNet: 0,
        categoryDiscountPercent: 0,
        categoryDiscount: 0,
        categoryDiscountNet: 0,
        vatId: 0,
        vatValue: 19,
        currency: 'EUR',
        interval: 'none',
        conversionFactor: 1,
        minimumOrderQuantity: '1.00',
        updatedAt: '2024-09-18 13:57:43',
        type: 'specialOffer',
        pricePosition: 99,
      },
    },
    graduatedPrices: [
      {
        price: {
          value: 90,
          formatted: 'EUR 90.00',
        },
        unitPrice: {
          value: 90,
          formatted: 'EUR 90.00',
        },
        basePrice: '',
        baseLot: null,
        baseUnit: null,
        baseSinglePrice: null,
        minimumOrderQuantity: 10,
        contactClassDiscount: {
          percent: 0,
          amount: 0,
        },
        categoryDiscount: {
          percent: 0,
          amount: 0,
        },
        currency: 'EUR',
        lowestPrice: {
          value: null,
          formatted: '',
        },
        vat: {
          id: 0,
          value: 19,
        },
        isNet: false,
        data: {
          salesPriceId: 4,
          price: 90,
          priceNet: 75.63025210084,
          basePrice: 90,
          basePriceNet: 75.63025210084,
          unitPrice: 90,
          unitPriceNet: 75.63025210084,
          lowestPrice: 0,
          lowestPriceNet: 0,
          customerClassDiscountPercent: 0,
          customerClassDiscount: 0,
          customerClassDiscountNet: 0,
          categoryDiscountPercent: 0,
          categoryDiscount: 0,
          categoryDiscountNet: 0,
          vatId: 0,
          vatValue: 19,
          currency: 'EUR',
          interval: 'none',
          conversionFactor: 1,
          minimumOrderQuantity: '10.00',
          updatedAt: '2024-09-18 13:57:43',
          type: 'default',
          pricePosition: 0,
        },
      },
      {
        price: {
          value: 95,
          formatted: 'EUR 95.00',
        },
        unitPrice: {
          value: 95,
          formatted: 'EUR 95.00',
        },
        basePrice: '',
        baseLot: null,
        baseUnit: null,
        baseSinglePrice: null,
        minimumOrderQuantity: 5,
        contactClassDiscount: {
          percent: 0,
          amount: 0,
        },
        categoryDiscount: {
          percent: 0,
          amount: 0,
        },
        currency: 'EUR',
        lowestPrice: {
          value: null,
          formatted: '',
        },
        vat: {
          id: 0,
          value: 19,
        },
        isNet: false,
        data: {
          salesPriceId: 3,
          price: 95,
          priceNet: 79.831932773109,
          basePrice: 95,
          basePriceNet: 79.831932773109,
          unitPrice: 95,
          unitPriceNet: 79.831932773109,
          lowestPrice: 0,
          lowestPriceNet: 0,
          customerClassDiscountPercent: 0,
          customerClassDiscount: 0,
          customerClassDiscountNet: 0,
          categoryDiscountPercent: 0,
          categoryDiscount: 0,
          categoryDiscountNet: 0,
          vatId: 0,
          vatValue: 19,
          currency: 'EUR',
          interval: 'none',
          conversionFactor: 1,
          minimumOrderQuantity: '5.00',
          updatedAt: '2024-09-18 13:57:43',
          type: 'default',
          pricePosition: 0,
        },
      },
      {
        price: {
          value: 100,
          formatted: 'EUR 100.00',
        },
        unitPrice: {
          value: 100,
          formatted: 'EUR 100.00',
        },
        basePrice: '',
        baseLot: null,
        baseUnit: null,
        baseSinglePrice: null,
        minimumOrderQuantity: 1,
        contactClassDiscount: {
          percent: 0,
          amount: 0,
        },
        categoryDiscount: {
          percent: 0,
          amount: 0,
        },
        currency: 'EUR',
        lowestPrice: {
          value: 80,
          formatted: 'EUR 80.00',
        },
        vat: {
          id: 0,
          value: 19,
        },
        isNet: false,
        data: {
          salesPriceId: 1,
          price: 100,
          priceNet: 84.033613445378,
          basePrice: 100,
          basePriceNet: 84.033613445378,
          unitPrice: 100,
          unitPriceNet: 84.033613445378,
          lowestPrice: 80,
          lowestPriceNet: 67.226890756303,
          customerClassDiscountPercent: 0,
          customerClassDiscount: 0,
          customerClassDiscountNet: 0,
          categoryDiscountPercent: 0,
          categoryDiscount: 0,
          categoryDiscountNet: 0,
          vatId: 0,
          vatValue: 19,
          currency: 'EUR',
          interval: 'none',
          conversionFactor: 1,
          minimumOrderQuantity: '1.00',
          updatedAt: '2024-09-18 13:49:14',
          type: 'default',
          pricePosition: 0,
        },
      },
    ],
  },
  facets: [],
  attributes: [],
  variationAttributeMap: {
    variations: [
      {
        variationId: 1145,
        isSalable: true,
        unitCombinationId: 1,
        unitId: 1,
        unitName: '1 piece',
        attributes: [],
      },
    ],
    attributes: [],
  },
};
