export const ProductMock = {
  defaultCategories: [
    {
      id: 73,
      parentCategoryId: null,
      level: 1,
      type: 'item',
      linklist: true,
      right: 'all',
      sitemap: true,
      updatedAt: '2022-04-27T18:12:56+02:00',
      manually: true,
      plentyId: 60796,
    },
  ],
  filter: {
    hasManufacturer: false,
    isSalable: true,
    isSalableAndActive: true,
    hasActiveChildren: false,
  },
  images: {
    all: [
      {
        url: 'https://cdn02.plentymarkets.com/mevofvd5omld/item/images/157/full/gear-headphones-01.png',
        width: 1430,
        names: [],
        urlSecondPreview:
          'https://cdn02.plentymarkets.com/mevofvd5omld/item/images/157/secondPreview/gear-headphones-01.png',
        urlPreview: 'https://cdn02.plentymarkets.com/mevofvd5omld/item/images/157/preview/gear-headphones-01.png',
        height: 1430,
        position: 0,
        urlMiddle: 'https://cdn02.plentymarkets.com/mevofvd5omld/item/images/157/middle/gear-headphones-01.png',
        path: 'S3:157:gear-headphones-01.png',
        cleanImageName: 'gear-headphones-01.png',
      },
    ],
    variation: [],
  },
  item: {
    id: 157,
    add_cms_page: '0',
    condition: {
      id: 0,
      names: {
        lang: 'de',
        name: 'Neu',
      },
    },
    storeSpecial: null,
    manufacturerId: 0,
    producingCountryId: 1,
    revenueAccount: 0,
    conditionApi: {
      id: 0,
      names: {
        lang: 'de',
        name: 'Neu',
      },
    },
    ageRestriction: 0,
    itemType: 'default',
    producingCountry: {
      names: {
        name: 'Deutschland',
        lang: 'de',
      },
      shippingDestinationId: 101,
      id: 1,
      active: 1,
      storehouseId: 0,
      lang: 'de',
      name: 'Germany',
      isoCode3: 'DEU',
      isCountryStateMandatory: null,
      isoCode2: 'DE',
    },
    manufacturer: [],
    rebate: 0,
    salableVariationCount: 1,
    customsTariffNumber: '',
  },
  variation: {
    position: 1,
    number: '1145',
    model: '',
    externalId: '',
    availabilityId: 1,
    maximumOrderQuantity: null,
    minimumOrderQuantity: 1,
    intervalOrderQuantity: 1,
    availableUntil: null,
    releasedAt: null,
    name: '',
    weightG: 0,
    weightNetG: 0,
    widthMM: 0,
    lengthMM: 0,
    heightMM: 0,
    unitsContained: 51,
    vatId: 0,
    bundleType: null,
    mayShowUnitPrice: true,
    customsTariffNumber: '',
    availability: {
      id: 1,
      icon: 'av1.gif',
      averageDays: 2,
      createdAt: '2022-06-27 09:20:16',
      updatedAt: '2022-06-27 09:20:16',
      names: {
        id: 41,
        availabilityId: 1,
        lang: 'de',
        name: 'Sofort versandfertig, Lieferzeit 48h',
        createdAt: '2022-06-27 09:20:16',
        updatedAt: '2022-06-27 09:20:16',
      },
      iconPath: '/tpl/availability/av1.gif',
    },
    id: 1100,
    unitCombinationId: 9,
    availabilityUpdatedAt: '2022-02-15T16:56:01+01:00',
  },
  texts: {
    id: 259,
    lang: 'de',
    name2: '',
    name3: '',
    description: '',
    itemId: 157,
    metaDescription: '',
    technicalData: '',
    urlPath: 'gear/headphones-capybara',
    name1: 'Headphones Capybara',
    shortDescription: '',
    keywords: '',
  },
  unit: {
    names: {
      unitId: 5,
      lang: 'de',
      name: 'Liter',
    },
    unitOfMeasurement: 'LTR',
    content: 2,
  },
  properties: [],
  hasOrderProperties: false,
  hasRequiredOrderProperty: false,
  prices: {
    default: {
      price: {
        value: 180,
        formatted: '180,00 EUR',
      },
      unitPrice: {
        value: 180,
        formatted: '180,00 EUR',
      },
      basePrice: '90,00 EUR / Liter',
      baseLot: 1,
      baseUnit: 'LTR',
      baseSinglePrice: 90,
      minimumOrderQuantity: 1,
      contactClassDiscount: {
        percent: 0,
        amount: 0,
      },
      categoryDiscount: {
        percent: 0,
        amount: 0,
      },
      currency: 'EUR',
      lowestPrice: {
        value: null,
        formatted: '',
      },
      vat: {
        id: 0,
        value: 19,
      },
      isNet: false,
      data: {
        salesPriceId: 1,
        price: 180,
        priceNet: 151.26050420168,
        basePrice: 180,
        basePriceNet: 151.26050420168,
        unitPrice: 180,
        unitPriceNet: 151.26050420168,
        lowestPrice: 100,
        lowestPriceNet: 100,
        customerClassDiscountPercent: 0,
        customerClassDiscount: 0,
        customerClassDiscountNet: 0,
        categoryDiscountPercent: 0,
        categoryDiscount: 0,
        categoryDiscountNet: 0,
        vatId: 0,
        vatValue: 19,
        currency: 'EUR',
        interval: 'none',
        conversionFactor: 1,
        minimumOrderQuantity: '1.00',
        updatedAt: '2022-02-15 16:56:11',
        type: 'default',
        pricePosition: 0,
      },
    },
    rrp: {
      price: {
        value: 250,
        formatted: '250,00 EUR',
      },
      unitPrice: {
        value: 250,
        formatted: '250,00 EUR',
      },
      basePrice: '125,00 EUR / Liter',
      baseLot: 1,
      baseUnit: 'LTR',
      baseSinglePrice: 125,
      minimumOrderQuantity: 0,
      contactClassDiscount: {
        percent: 0,
        amount: 0,
      },
      categoryDiscount: {
        percent: 0,
        amount: 0,
      },
      currency: 'EUR',
      lowestPrice: {
        value: null,
        formatted: '',
      },
      vat: {
        id: 0,
        value: 19,
      },
      isNet: false,
      data: {
        salesPriceId: 2,
        price: 250,
        priceNet: 210.08403361345,
        basePrice: 250,
        basePriceNet: 210.08403361345,
        unitPrice: 250,
        unitPriceNet: 210.08403361345,
        lowestPrice: 100,
        lowestPriceNet: 100,
        customerClassDiscountPercent: 0,
        customerClassDiscount: 0,
        customerClassDiscountNet: 0,
        categoryDiscountPercent: 0,
        categoryDiscount: 0,
        categoryDiscountNet: 0,
        vatId: 0,
        vatValue: 19,
        currency: 'EUR',
        interval: 'none',
        conversionFactor: 1,
        minimumOrderQuantity: '0.00',
        updatedAt: '2023-09-14 14:48:22',
        type: 'rrp',
        pricePosition: 0,
      },
    },
    set: null,
    specialOffer: null,
    graduatedPrices: [
      {
        price: {
          value: 180,
          formatted: '180,00 EUR',
        },
        unitPrice: {
          value: 180,
          formatted: '180,00 EUR',
        },
        basePrice: '90,00 EUR / Liter',
        baseLot: 1,
        baseUnit: 'LTR',
        baseSinglePrice: 90,
        minimumOrderQuantity: 1,
        contactClassDiscount: {
          percent: 0,
          amount: 0,
        },
        categoryDiscount: {
          percent: 0,
          amount: 0,
        },
        currency: 'EUR',
        lowestPrice: {
          value: null,
          formatted: '',
        },
        vat: {
          id: 0,
          value: 19,
        },
        isNet: false,
        data: {
          salesPriceId: 1,
          price: 180,
          priceNet: 151.26050420168,
          basePrice: 180,
          basePriceNet: 151.26050420168,
          unitPrice: 180,
          unitPriceNet: 151.26050420168,
          lowestPrice: 100,
          lowestPriceNet: 100,
          customerClassDiscountPercent: 0,
          customerClassDiscount: 0,
          customerClassDiscountNet: 0,
          categoryDiscountPercent: 0,
          categoryDiscount: 0,
          categoryDiscountNet: 0,
          vatId: 0,
          vatValue: 19,
          currency: 'EUR',
          interval: 'none',
          conversionFactor: 1,
          minimumOrderQuantity: '1.00',
          updatedAt: '2022-02-15 16:56:11',
          type: 'default',
          pricePosition: 0,
        },
      },
    ],
  },
  facets: [],
  attributes: [],
  variationAttributeMap: {
    variations: [
      {
        variationId: 1100,
        isSalable: true,
        unitCombinationId: 9,
        unitId: 5,
        unitName: '2 Liter',
        attributes: [],
      },
    ],
    attributes: [],
  },
};
