services:
  unleash:
    image: unleashorg/unleash-server:latest
    ports:
      - '4242:4242'
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/unleash
      DATABASE_SSL: 'false'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: unleash
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - unleash_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  unleash_postgres:
