import {
  AllowedHTTPMethods,
  BasicAuth,
  CrossOriginEmbedderPolicyValue,
  CrossOriginOpenerPolicyValue,
  CrossOriginResourcePolicyValue,
  HTTPMethod,
  RateLimiter,
  ReferrerPolicyValue,
  XDnsPrefetchControlValue,
  XFrameOptionsValue,
  XPermittedCrossDomainPoliciesValue,
} from 'nuxt-security';

export const securityConfiguration = {
  strict: false,
  headers: {
    crossOriginResourcePolicy: 'same-origin' as CrossOriginResourcePolicyValue,
    crossOriginOpenerPolicy: 'same-origin' as CrossOriginOpenerPolicyValue,
    crossOriginEmbedderPolicy: 'credentialless' as CrossOriginEmbedderPolicyValue,
    contentSecurityPolicy: {
      'base-uri': ["'none'"],
      'font-src': ["'self'", 'https:', 'data:'],
      'form-action': ["'self'"],
      'frame-ancestors': ["'self'"],
      'img-src': ["'self'", 'data:'],
      'object-src': ["'none'"],
      'script-src-attr': ["'none'"],
      'style-src': ["'self'", 'https:', "'unsafe-inline'"],
      'script-src': ["'self'", 'https:', "'unsafe-inline'", "'strict-dynamic'", "'nonce-{{nonce}}'"],
      'upgrade-insecure-requests': true,
    },
    originAgentCluster: '?1' as const,
    referrerPolicy: 'no-referrer' as ReferrerPolicyValue,
    strictTransportSecurity: {
      maxAge: 15_552_000,
      includeSubdomains: true,
    },
    xContentTypeOptions: 'nosniff' as const,
    xDNSPrefetchControl: 'off' as XDnsPrefetchControlValue,
    xDownloadOptions: 'noopen' as const,
    xFrameOptions: 'SAMEORIGIN' as XFrameOptionsValue,
    xPermittedCrossDomainPolicies: 'none' as XPermittedCrossDomainPoliciesValue,
    xXSSProtection: '0',
    permissionsPolicy: {
      camera: [],
      'display-capture': [],
      fullscreen: [],
      geolocation: [],
      microphone: [],
    },
  },
  requestSizeLimiter: {
    maxRequestSizeInBytes: 2_000_000,
    maxUploadFileRequestInBytes: 8_000_000,
    throwError: true,
  },
  rateLimiter: {
    tokensPerInterval: 150,
    interval: 300_000,
    headers: false,
    driver: {
      name: 'lruCache',
    },
    throwError: true,
  } as RateLimiter,
  xssValidator: {
    throwError: true,
  },
  corsHandler: {
    origin: 'http://localhost:3000',
    methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE'] as HTTPMethod[],
    preflight: {
      statusCode: 204,
    },
  },
  allowedMethodsRestricter: {
    methods: '*',
    throwError: true,
  } as AllowedHTTPMethods,
  hidePoweredBy: true,
  basicAuth: false as false | BasicAuth,
  enabled: true,
  csrf: false,
  nonce: true,
  removeLoggers: true,
  ssg: {
    meta: true,
    hashScripts: true,
    hashStyles: false,
    nitroHeaders: true,
    exportToPresets: true,
  },
  sri: true,
};
