const errorMapping: Record<number, string> = {
  18: 'GUI_EXCEPTION_MIN_ORDER_VALUE_NOT_REACHED',
  51: 'GUI_EXCEPTION_NOT_USABLE_FOR_SPECIAL_OFFER',
  70: 'GUI_EXCEPTION_ALREADY_USED_OR_INVALID_COUPON_CODE',
  78: 'GUI_EXCEPTION_CAMPAIGN_EXPIRED',
  126: 'GUI_EXCEPTION_NO_MATCHING_ITEM_IN_BASKET',
  329: 'GUI_EXCEPTION_COUPON_ONLY_SUBSCRIPTION',
  330: 'GUI_EXCEPTION_COUPON_ONLY_SINGLE_USAGE',
  331: 'GUI_EXCEPTION_NO_OPEN_AMOUNT',
  332: 'GUI_EXCEPTION_EXPIRED',
  334: 'GUI_EXCEPTION_COUPON_ONLY_FOR_NEW_CUSTOMERS',
  335: 'GUI_EXCEPTION_COUPON_ONLY_FOR_EXISTING_CUSTOMERS',
  336: 'GUI_EXCEPTION_COUPON_WRONG_CUSTOMER_GROUP',
  337: 'GUI_EXCEPTION_COUPON_WRONG_CUSTOMER_TYPE',
  338: 'GUI_EXCEPTION_COUPON_NO_CUSTOMER_TYPE_PROVIDED',
  339: 'GUI_EXCEPTION_COUPON_NO_CUSTOMER_TYPE_ACTIVATED',
  340: 'GUI_EXCEPTION_COUPON_NO_CUSTOMER_GROUP_ACTIVATED',
  341: 'GUI_EXCEPTION_CAMPAIGN_NO_WEBSTORE_ACTIVATED',
  342: 'GUI_EXCEPTION_CAMPAIGN_WRONG_WEBSTORE_ID',
  343: 'GUI_EXCEPTION_CAMPAIGN_NO_WEBSTORE_ID_GIVEN',
  344: 'GUI_EXCEPTION_NO_REDEMTION_FOR_CODE',
  345: 'GUT_EXCEPTION_TOO_MANY_PROMOTION_CODES',
  1070: '',
};

export const getErrorCode = (code: number): string | undefined => {
  return errorMapping[code];
};
