export const paths = {
  home: '/',
  category: '/',
  product: '/product/',
  cart: '/cart',
  wishlist: '/wishlist',
  checkout: '/checkout',
  readonlyCheckout: '/readonly-checkout',
  search: '/search',
  account: '/my-account/personal-data',
  thankYou: '/thank-you',
  accountPersonalData: '/my-account/personal-data',
  accountBillingDetails: '/my-account/billing-details',
  accountShippingDetails: '/my-account/shipping-details',
  accountMyOrders: '/my-account/my-orders',
  accountMyWishlist: '/my-account/wishlist',
  accountReturns: '/my-account/returns',
  authResetPassword: '/reset-password',
  authResetPasswordSuccess: '/reset-password-success',
  authLogin: '/login',
  privacyPolicy: '/PrivacyPolicy',
  termsAndConditions: '/TermsAndConditions',
  cancellationRights: '/CancellationRights',
};
