const DEFAULT_ITEMS_PER_PAGE = 50;
const DEFAULT_FEEDBACK_ITEMS_PER_PAGE = 10;
const DEFAULT_PAGE = 1;
const DEFAULT_FEEDBACK_PAGE = 1;
const DEFAULT_QUICK_CHECKOUT_TIMER = 10;
const PER_PAGE_STEPS: number[] = [10, 20, 50, 100];
const ESSENTIAL_COOKIES_INDEX = 0;
const PREVIEW_COOKIES: string[] = ['pwa'];

export const defaults = {
  DEFAULT_ITEMS_PER_PAGE,
  DEFAULT_PAGE,
  PER_PAGE_STEPS,
  DEFAULT_FEEDBACK_PAGE,
  DEFAULT_FEEDBACK_ITEMS_PER_PAGE,
  DEFAULT_QUICK_CHECKOUT_TIMER,
  ESSENTIAL_COOKIES_INDEX,
  PREVIEW_COOKIES,
};
