const DEFAULT_ITEMS_PER_PAGE = 50;
const DEFAULT_PAGE = 1;
const PER_PAGE_STEPS: number[] = [10, 20, 50, 100];
const ESSENTIAL_COOKIES_INDEX = 0;

export const defaults = {
  DEFAULT_ITEMS_PER_PAGE,
  DEFAULT_PAGE,
  PER_PAGE_STEPS,
  ESSENTIAL_COOKIES_INDEX,
};
