name: OS Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable corepack
        run: corepack enable

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '20.5'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'

      - name: Set yarn version
        run: |
          yarn set version stable
          yarn set version 3.6.4

      - name: Setup .yarnrc.yml
        run: |
          yarn config set nodeLinker node-modules
          yarn config set npmScopes.plentymarkets.npmRegistryServer "https://npm.pkg.github.com"
          yarn config set npmScopes.plentymarkets.npmAlwaysAuth true
          yarn config set npmScopes.plentymarkets.npmAuthToken $NODE_AUTH_TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment
        run: |
          touch apps/web/.env
          cat <<EOT >> apps/web/.env
          API_SECURITY_TOKEN=${{ secrets.API_SECURITY_TOKEN }}
          API_ENDPOINT=https://mevofvd5omld.c01-14.plentymarkets.com
          DEFAULT_FEEDBACK_ITEMS_PER_PAGE=1
          ${{ vars.CONFIG }}
          EOT

      - name: Install dependencies
        run: yarn --immutable

      - name: Build app
        run: |
          yarn build