name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: 0 8 * * *

permissions:
  contents: read
  id-token: write
  pages: write
  packages: read

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  get-pwa:
    name: Get PWA documentation
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            repository: 'plentymarkets/plentyshop-pwa'

        - name: Setup Node
          uses: ./.github/actions/setup
  
        - name: Build typedoc
          run: cd apps/web && npm run publish-typedoc
  
        - name: Upload artifact
          uses: actions/upload-artifact@v4
          with:
            name: pwa-docs
            path: ${{ github.workspace }}/apps/web/docs/reference/
  
  get-sdk:
    name: Get SDK documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            repository: 'plentymarkets/plentymarkets-sdk'
            token: ${{ secrets.ORGA_PAT_CICD1_FULL_REPO_AND_PACKAGES }}

      - name: Setup Node
        uses: ./.github/actions/setup

      - name: Build typedoc
        run: npm run publish-typedoc
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sdk-docs
          path: ${{ github.workspace }}/docs/reference/

  build:
    name: Build & publish site
    runs-on: ubuntu-latest
    needs: [get-pwa, get-sdk]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download sdk-docs
        uses: actions/download-artifact@v4
        with:
            name: sdk-docs
            path: ${{ github.workspace }}/reference/
      - name: Download pwa-docs
        uses: actions/download-artifact@v4
        with:
            name: pwa-docs
            path: ${{ github.workspace }}/reference/
      
      - name: Enable corepack
        run: corepack enable
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Set yarn version
        run: |
          yarn set version stable
          yarn set version 3.6.4

      - name: Setup .yarnrc.yml
        run: |
            yarn config set nodeLinker node-modules
      - name: Install dependencies
        run: yarn install
      - name: Build with VitePress
        run: |
          yarn docs:build
          touch .vitepress/dist/.nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .vitepress/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
