name: Release Notification
on:
  release:
    types: [created]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Push release notification
        run: |
          curl --location --request POST '${{ secrets.CHAT_WEBHOOK_SBS_AREA }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "cardsV2": [
                {
                    "cardId": "${{ github.event.release.version }}",
                    "card": {
                        "header": {
                            "title": "New release created!",
                            "subtitle": "Version: ${{ github.event.release.version }}"
                        },
                        "sections": [
                            {
                                "widgets": [
                                    {
                                        "buttonList": {
                                            "buttons": {
                                                "text": "Open release",
                                                "onClick": {
                                                    "openLink": {
                                                        "url": "https://github.com/${{ github.repository }}/releases/tag/${{ github.event.release.version }}"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]}'
